getting-things-gnome/gtg

- CHANGELOG
- GTG/gtk/editor/taskview.py
Check wheather TextTag has link attribute or not
Fixes #177
> Check TextTag attribute

- GTG/gtk/browser/browser.py
This PR fixes #221 
When the string is empty it automatically goes out of search mode and removes the filter (showing all tags)
> Fix search

- tests/core/test_config.py
> Fix AttributeError: assert_called

- GTG/gtk/browser/browser.py
This PR fixes the wrong tasks being deleted from the closed view
Also fixes #168
> Detect selected pane as fallback for selection

- GTG/gtk/browser/browser.py
- GTG/gtk/delete_dialog.py
- GTG/gtk/manager.py
This technically fixes the missing icon issue because these dialogs don't use icons anymore.
> Use Gtk.MessageDialog for the task delete dialog

- gtg.sh
- scripts/debug.sh
- scripts/generate_mofile.sh
- scripts/generate_potfile.sh
- scripts/import_my_tasks_into_debug_tasks.sh
Minor cleanup of the shell scripts to fix common shellcheck warnings and errors
> Shellcheck fixes

- GTG/gtk/browser/main_window.py
- GTG/gtk/data/context_menus.ui
> Added due date "Now" in main window right click

- po/zh_CN.po
Signed-off-by: Chenxiong Qi <qcxhome@gmail.com>
> Translate part of zh_CN.po

- GTG/gtk/browser/treeview_factory.py
Behold, the greatest string wrangling of all time.
This fixes issue #357 and issue #375
Tested and works on my end. If the changes look good to you at least from a theoretical standpoint, then I can push them and there will be much rejoicing.
> Task treeview fixes

- GTG/backends/unmaintained/backend_rtm.py
- GTG/core/dirs.py
- GTG/plugins/export/export.py
- README.md
- flatpak/org.gnome.GTG-stable.json
- flatpak/org.gnome.GTG.json
- requirements.txt
- scripts/anonymize_task_file.py
> Replace XDG related functions

- GTG/gtk/browser/main_window.py
The config entry existed, but from what I can tell it is never used (read nor written to).
This uses the same convention as get_selected_pane(), because it looks nice when peeking at the config.
Thus, this could have been done simpler by just using the "internal" child name of the GtkStack.
If that is desired, I can change that easily.
Fixes #398
> Save and restore task view in the main window

- docs/contributors/translating.md
Basically my current workflow. Feedback welcome!
Assumes that the translator deals with the files directly and not use like an web interface to translate or something.
fixes #305
> Add translation contributor document

- GTG/gtk/browser/main_window.py
> set application id as logo icon in about window

- GTG/gtk/data/task_editor.ui
- GTG/gtk/editor/editor.py
- GTG/gtk/editor/recurring_menu.py
- po/POTFILES.in
> Fix current recurring state translation issue

- GTG/core/dates.py
- GTG/core/task.py
- GTG/gtk/browser/treeview_factory.py
A while ago in September I tried to optimize the startup with many tasks currently unsuccessfully. In the meanwhile I did those micro optimizations, they shouldn't change much. See the commits for more info.
I haven't really tested them since them, but they are relatively simple enough.
BTW, in `dates.py`, at the file level, `FUNCS` is initialized with some `datetime` objects with being relative to "today", but AFAIK the value isn't updated after a new day. Not sure if this is significant (or where this is used), but I'll just point this out here.
```python
FUNCS = {
NOW: datetime.date.today(),
SOON: datetime.date.today() + datetime.timedelta(15),
SOMEDAY: datetime.date.max,
NODATE: datetime.date.max - datetime.timedelta(1),
}
```
> Some micro optimizations

- GTG/gtk/data/help_overlay.ui
Updated UI to add the treeview expand/collapse shortcuts.
> Update Keyboard Shortcut UI for #408

- GTG/plugins/dev_console.gtg-plugin
- GTG/plugins/dev_console.gtg-plugin.desktop
- GTG/plugins/dev_console/__init__.py
- GTG/plugins/dev_console/buffer.py
- GTG/plugins/dev_console/console.py
- GTG/plugins/dev_console/meson.build
- GTG/plugins/dev_console/utils.py
- GTG/plugins/dev_console/window.py
- GTG/plugins/meson.build
The developer console plugin. ~Ripped off~ _Based on_ the Developer Console plugin from Pitivi.
To test this:
1. Enable the plugin
2. Press F12 or open the window from the main menu
3. Type away and mess with it
Here's an example:
```python
>>> t = req.new_task()
>>> t.set_title('Task created from code')
True
```
> Developer Console

- GTG/gtk/browser/cell_renderer_tags.py
- GTG/gtk/browser/simple_color_selector.py
- GTG/gtk/browser/tag_editor.py
- GTG/gtk/data/style.css
Replace the old icons with shiny new emojis. 
Testing appreciated!
closes #85
> Replace icons with emojis

- GTG/plugins/hamster.gtg-plugin
> adding dbus as dependency to hamster plugin.

- GTG/gtk/browser/main_window.py
Use a timer for live search (taken from taskview)
fixes #281
> Use a timer for live search

- docs/user_manual/C/gtg-shortcut-keys.page
- docs/user_manual/C/gtg-subtasks.page
I think this was the only little thing that I missed since the last docs PR. I went through our closed PRs and items since then, and I think this is all up-to-date at this point. Any other items that would affect the user manual look to be slated for 0.6, so I think I am done for this release :) .
> Updates to manual for adding parent task to existing task (#517)

- GTG/gtk/browser/main_window.py
> Search query gets inserted into quick-add entry

- GTG/gtk/browser/main_window.py
- GTG/gtk/data/main_window.ui
Implements #141 
Expose two new buttons in the hamburger menu to collapse/expand all tasks.
> Add Collapse and Expand all tasks buttons

- GTG/core/xml.py
> Remove fake update_date when task is not repeating

- GTG/gtk/data/main_window.ui
Before while pressing the down and up arrow keys:
https://user-images.githubusercontent.com/1196130/117217958-93563480-ae02-11eb-8104-69c85d242f7d.mp4
After: What you would expect how it should behave.
> Fix certain main menu entries not being selectable via keyboard

- GTG/core/requester.py
- GTG/core/task.py
- GTG/core/xml.py
- GTG/plugins/gamify.gtg-plugin
- GTG/plugins/gamify/gamify.py
> Fix gamfiy bugs

- README.md
Fixes #679
This is why I wanted to test it first. Looks fine from the man page, but haven't actually tested it yet (need to spin up VMs...), but I trust the issuer.
> README: Don't overwrite sources.list with the backports

- GTG/backends/__init__.py
Backend loading imports all the files in `GTG/backends/` and, if the import succeed, consider the module to be one that contains an actual Backend implementation. It's false at least for `backend_signals`. 
I try to fix that approach by only listing as an actual backend module the one that contains a subclass of `GenericBackend` to some extent.
> Fixing backend loading

- GTG/gtk/application.py
- GTG/gtk/browser/main_window.py
- GTG/gtk/data/context_menus.ui
- GTG/gtk/data/help_overlay.ui
- GTG/gtk/editor/editor.py
This change replaces the current "Mark as Not Done" and "Undismiss" options when right clicking a closed task with a single "Reopen" option as suggested in #377.
This is my first time contributing to an open source project, so let me know if there is anything that I need to change.
> Unified 'Reopen' action (#377)

- CONTRIBUTING.md
- docs/contributors/contributing to the user manual.md
This PR is to address #609. This includes all of the getting started materials I used when starting on the project. I wanted to include helpful links and troubleshooting tips for someone who does not have a programming background.
> Add Documentation for Contributing to the User Manual

- README.md
- docs/contributors/bug reporting and triaging.md
- docs/contributors/release process and checklist.md
- docs/contributors/test suite - coverage testing.md
- docs/source/man/gtg.rst
This is pretty much trivial stuff I wanted to correct, that has been sitting around in my todo list for way too long ;)
Probably should not break anything or be inaccurate, but making a pull request out of it just in case. Would recommend fast-forward (rebase-type) merging (which is also probably a policy we should encourage/document somewhere...).
> Minor updates to contributors documentation

- docs/user_manual/C/gtg-complete-delete-dismiss-task.page
After working on NEWS, I realized I forgot to update this page when I was updating the rest of the user manual. I missed this feature. Includes minor changes to page. I tested everything else on the page/updated text as needed.
> Update create-dismiss-delete for Reopen action

- GTG/core/dates.py
> fixes #765

- GTG/core/dates.py
I tried rewriting the whole function to make more clean and clear.
> Cleanup _parse_only_month_day_for_recurrency

- docs/user_manual/C/gtg-sync.page
This documents a technique I've been using since the onset of GTG, as an alternative serverless manual/batch sync trick. It doesn't go in depth about it, but presents the possibility, which may help some users.
> User docs: mention the possibility of using Unison to manually sync data

- GTG/core/plugins/__init__.py
Small text changes that bugged me while I was first updating the translation of GTG to german.
> Improve plugin error messages english

- po/pl.po
Updated Polish translation - full and current
> Polish translation update

- po/hu.po
@diegogangl I have done the rebase and also added those extra translations. Thanks a lot.
> Updating Hungarian translation

- po/pl.po
Small fixes for Polish translation.
> Polish translation fixes

- GTG/core/config.py
- GTG/core/plugins/api.py
- GTG/gtk/browser/main_window.py
- GTG/gtk/data/calendar.ui
- GTG/gtk/data/general_preferences.ui
- GTG/gtk/data/main_window.ui
- GTG/gtk/data/modify_tags.ui
- GTG/gtk/data/plugins.ui
- GTG/gtk/data/preferences.ui
- GTG/gtk/data/style.css
- GTG/gtk/data/tag_editor.ui
- GTG/gtk/data/task_editor.ui
- GTG/gtk/editor/calendar.py
- GTG/gtk/editor/editor.py
- GTG/gtk/editor/taskview.py
- GTG/plugins/dev_console/console.py
- GTG/plugins/export/export.py
- GTG/plugins/send_email/sendEmail.py
- GTG/plugins/untouched_tasks/untouchedTasks.py
- docs/contributors/plugin development guide.md
Includes cherry picks from @ranchester2 's Gtk4 branch, updated to the latest changes in master. This PR leaves us "at the edge" of moving to Gtk4.
> Preparing for Gtk4 - Part 2

- run-tests
- tests/backend/backend_caldav_test.py
> Fixing Github Actions not failing on broken test suit

- GTG/gtk/errorhandler.py
Just in case it matters, and wanting to trying out to get the dev version of GTG running inside flatpak.
> Error handler: Add Flatpak infos

- GTG/gtk/browser/sidebar_context_menu.py
Small documentation and formatting fixes in the `sidebar_context_menu`.
> Fixes in sidebar_context_menu.py

- GTG/core/config.py
- GTG/gtk/browser/main_window.py
Save sort configurations and reload on startup
Also remove a duplicated method
closes #1020
closes #353
> Save sort setting in config

- data/org.gnome.GTG.appdata.xml.in.in
- Add missing developer block
- Update homepage to github page, due to the wiki page are going to be retired.
- Add vcs-browser URL
- Update translation URL
- Remove the none aors rules
- Fix the updatecontact tag
- Copy screenshots to the repository
> Fix appdata related issues

- GTG/core/config.py
- GTG/gtk/application.py
- GTG/gtk/browser/main_window.py
- GTG/gtk/browser/sidebar.py
Saves and restores selected tag on startup
closes #551
> Restore selected tag on startup

- GTG/gtk/browser/sidebar.py
This solves a bit of #390, the other part would require bigger architecture changes.
ref #390
> Unset searches when unselecting saved searches

- GTG/gtk/browser/main_window.py
@diegogangl it looks like you may not have set up pre-commit on your dev machine?
```
pip install pre-commit
pre-commit install
```
then pre-commit will automatically fix this sort of thing.
> Remove whitespace to please pre-commit

- GTG/backends/backend_signals.py
- GTG/core/borg.py
- GTG/core/filters.py
- GTG/core/keyring.py
- GTG/core/networkmanager.py
- GTG/core/plugins/api.py
- GTG/core/plugins/engine.py
- GTG/core/sorters.py
- GTG/core/timer.py
- add simple missing type annotations
- suppress errors for untyped parts
> Small type fixes for core

- GTG/gtk/browser/main_window.py
> Fix focusing on new sidebar

- GTG/gtk/action_row.py
- GTG/gtk/browser/__init__.py
- GTG/gtk/data/action_row.ui
- GTG/gtk/data/general_preferences.ui
- GTG/gtk/general_preferences.py
- GTG/gtk/meson.build
This makes the rows work better in the preferences dialog (they should now react when clicking on them)
> Introduce ActionRow widget and port to them

- GTG/gtk/browser/task_pane.py
- GTG/gtk/data/general_preferences.ui
- GTG/gtk/data/style.css
- GTG/plugins/gamify/prefs.ui
- GTG/plugins/hamster/prefs.ui
Related: https://github.com/getting-things-gnome/gtg/issues/1197
> Port lists to standard list styles

- GTG/gtk/browser/sidebar.py
- GTG/gtk/browser/sidebar_context_menu.py
> Disable edit button when multiple tags are selected

- GTG/core/tasks.py
> Notify change in row css when detagging

- GTG/core/datastore.py
PR #1233 did a good job speeding up the program startup. However, there are other scenarios that can trigger frequent recalculations (e.g., deleting many tasks, syncing backends, etc.), which can be slow with a large dataset. Constantly disabling and enabling recalculations would pollute the source code, so I decided to look for a different solution.
Luckily, [GLib.idle_add](https://docs.gtk.org/glib/func.idle_add.html) can schedule the recalculation to run after all of these changes have been made. Since these values are only used in the UI to inform the user, we shouldn't worry about any other functionality being affected.
> Use GLib.idle_add to schedule the recalculation of sidebar counters

- GTG/core/config.py
- GTG/gtk/browser/task_pane.py
- GTG/gtk/data/general_preferences.ui
- GTG/gtk/data/style.css
- GTG/gtk/general_preferences.py
Fixes #1013
**The main changes are as follows:**
- extend the default config,
- extend the preferences window with the new option,
- dynamically add and remove a CSS class to the `TaskBox`.
> Implement a preference for compact mode
