README.md

Hi, I noticed that there is a minor error in the README.md file. It has a command that says 
$ yelp doc/userdoc/C/index.page
the doc folder doesn't exist in the gtg repository, which led in me getting an error while running that so instead I changed that to  docs which is the correct name of the folder according to the gtg repository. 
$ yelp docs/userdoc/C/index.page
I hope this little change is helpful.

Minor error in the README.md docs instead of doc

---

GTG/core/config.py
GTG/gtk/browser/browser.py
GTG/gtk/browser/taskbrowser.ui

This pull request introduces HeaderBar into the GTG app.
I have included the most essential buttons and functionality which had to be removed from the menu and toolbar. Now they provide the very basic functionality so as to allow normal, comfortable use.
Other:
- refurbished keyboard shortcuts in order to preserve the ease of use as before
- some functions which may not be currently in use have been preserved so as to allow their use in a short period of time when I implement stack switcher or other features.
- over the course of the upcoming months, when the design polishes, the text buttons will be probably changed by representative icons.
Please, note that the centred three buttons will be redesigned into a StackSwitcher shortly, now they are being included only as normal buttons due …

Headerbar implementation into GTG!

---

GTG/core/requester.py
GTG/gtk/browser/browser.py
GTG/gtk/browser/taskbrowser.ui

In this commit, I am implementing GtkStack in order to enable switching between task views in a more
coherent way. The transition is set at 'crossfade' as of now, as I found that one quite elegant and simplistic.
Introduction of this cool feature included:
* Removing old GtkNotebook elements and using GtkStack instead
* Creation of new widgets and minor code cleaning in order to remove all the unused functions.
* I left one TODO note next to _add_accelerator_for_widget function, as I could not get the feature to work in this new code. Please either help or comment on how to do it, I'll give a separate PR.
* EXTRA: I used an icon instead of the label "Settings", in order to make the headerbar a bit nicer and not so cluttered.
Note: right-click menu in closed tasks does not work 100% …

Implement the stack switcher into the GTG app

---

GTG/gtk/backends_dialog/__init__.py

The on_help of the BackendsDialog method should be a classmethod like
the one from the PreferencesDialog.
(Found while testing out @quantifiedcode)

BackendsDialog: Declare on_help as classmethod

---

GTG/plugins/geolocalized_tasks/geolocalized_tasks.py

**This PR solves #92**
I'm removing a left-behind ImageMenuItem widget and putting MenuItem instead.
It would be complicated to keep there the image. If you look at the documentation of ImageMenuItem it suggests creating a MenuItem, placing a Box inside and within that box place a Lable and an Image which would be a real mess to do in code!

Remove GtkImageMenuItem occurence

---

GTG/core/treefactory.py
GTG/gtk/browser/browser.py
GTG/gtk/browser/taskbrowser.ui
GTG/gtk/browser/treeview_factory.py

Hi guys, this PR includes a few changes to the UI to bring it more in line with the current HIG and general UI style.
- Moved tags, synchronization, plugins and preferences to a main (burger) menu
- Brought back About and Help which were probably lost in the app menu
- Removed "tasks" from the names of the tabs to avoid repetition
- Added emoji input and button to quick entry. (I don't know if the button is really needed TBH, but it does look nice)
- Removed double borders in the sidebar
- Added some padding to the quick entry to avoid double edges there too
- Improved the padding in the sidebar
- Used symbolic icons for sidebar
There are two issues:
- The F9 shortcut only works if the main menu popup is open. I couldn't figure out how to fix this. Maybe we need to add a custom signal to …

UI Polish / Improvements

---

GTG/gtk/editor/editor.py
GTG/gtk/ui/taskeditor.ui

This PR removes the bold/italic buttons (they can be brought back when they are implemented). It also adds padding to a bunch of popups and fixes the icon menu for the task editor.
It also removes the checkbox from the tags popup and adds tags just by clicking their name.
This is closer to the old gtg behaviour. The checkbox was added so that tags could also be removed from the menu, but since that's not implemented unchecking the the checkbox did nothing (which is kind of weird for the user).

Remove editor new features

---

CHANGELOG
GTG/gtk/browser/browser.py

Added shortcut key "F1" to open help
Fixes #189

Help not accessible from main window

---

tests/core/test_config.py

Trivial fix, but now all the tests pass!
Signed-off-by: Olivier Mehani shtrom@ssji.net

Fix test_falls_back_when_there_is_config_error

---

requirements.txt

These two packages are required when trying to run GTG from a local
virtual environment by executing script gtg.sh
Signed-off-by: Chenxiong Qi <qcxhome@gmail.com>

Add missing dependent packages

---

scripts/debug.sh

The option is gone from main gtg binary since commit 5131f6fae6c4efed,
where it was also dropped from debug.sh script, but appears it was
forgotten to be dropped from the usage help string.

debug.sh: Drop -l from usage help as it is not a valid option anymore

---

GTG/tools/keyring.py

This happens when GNOME Keyring is not found.

gi.require_version raises uncatched exception

---

.gitignore
Makefile
requirements.txt
tox.ini

Tox is a widely spread testing automation tool for python projects,
it still uses the Makefile under the hood, but tox will take care
of managing virtualenvs and running the tests inside of them.

Add tox support

---

README.md

Avoid redirect from http://live.gnome.org/gtg/ to https://wiki.gnome.org/Apps/GTG.

Fix link to GTG wiki in README

---

GTG/gtk/browser/tag_context_menu.py

Deleting the tag in this case doesn't do anything since it's actually a saved search, without a '@' prepended to the text.
Fixes #283 
There is a bigger issue here, in that it doesn't seem possible to actually alter the search term(s) once the search has been saved. So having a "Edit Search..." option that just displays the same window as for editing tags is misleading. Probably the "Edit Tag..." option should not be displayed at all for saved searches. Instead there should be a window specifically for editing saved searches, which actually allows you update the saved search terms. I thought that was probably out of scope for this ticket.

Hide delete tag option in context menu for saved search

---

GTG/gtk/application.py

webbrowser python module just opens things in the browser for me, which
doesn't understand what a "help:gtg" is and routes it back to external
program dialog if lucky.
Use Gtk.show_uri instead, which will properly open it in help handler (yelp).
I believe we should be using Gtk.show_uri instead of webbrowser in other
places as well, but that's something for a different release.

Fix opening of the help files

---

GTG/gtk/data/main_window.ui

The open tasks view (to view all open tasks) is rightfully called "Open", however, it is also used as an verb (like in the Export plugin).
This is problematic for languages that has distinct words for those two situations (such as in german: "Offen" for the former one, and "Öffnen" for the latter one).
Because the latter is the more "usual" case, the name of the view names get an special gettext message context.
Note that this means translators would have to re-check the translation as it would be marked as fuzzy by gettext.
From very little testing (as I am not very familiar with the gettext tools), it did that for me, but also correctly separated the "Open" from the export plugin and the "Open" from the task view name in the main window.

Add translation context for the tasks view names

---

GTG/plugins/export/export.py

Looks like since the GTK3 Headerbar switch, the new menus use ModelButtons instead of the old MenuItems.
[Fixes the comment by nekohayo](https://github.com/getting-things-gnome/gtg/issues/299#issuecomment-638259673) in #299.
Found using the [GTK Inspector](https://developer.gnome.org/gtk3/3.24/gtk-running.html#interactive-debugging) (Ctrl+Shift+i doesn't work for some reason, I used `GTK_DEBUG=interactive ./launch.sh`: (The export plugins menu entry is called "Exportiere die aktuell gelistete Aufgaben" here)
Note that the plugin itself seems to be buggy, I couldn't export anything (to check what it really exports, like does it take into account the current filter being applied?)
When trying to export (using the open button), I just get an error message that the document couldn't be …

Export plugin: Make it clickable in the menu

---

GTG/gtg.in

When python is built without gettext support these functions aren't
available and as such GTG fails to start without this change.

Gracefully handle locale.{bind,}textdomain not being available

---

GTG/plugins/untouched_tasks/untouchedTasks.ui

Current upper limit in Untouched Task timer is 100 days, which seems
arbitrary and might confuse users.
Since the Entry widget for the timer is limited to show up to 3 digits,
it seems more reasonable to set this upper limit to 999 days.
Closes #412

Fix Untouched Task timer upper limit

---

GTG/gtk/browser/main_window.py
GTG/gtk/data/main_window.ui
GTG/gtk/editor/editor.py

Disable delete task shortcut when focus is in quick entry or task editor.
why someone could want to use `Ctrl+Delete` in an editor? Because that's the standard way to delete the word that is after the text cursor (the opposite of Ctrl+Backspace)
To do it we add a signal to catch event on focus in and focus out to remove `ctrl+del` accelerator or add it respectively.

Disabled "ctrl+del" on text focus #352 

---

GTG/core/dates.py
GTG/core/firstrun_tasks.py
GTG/core/task.py
GTG/core/xml.py
GTG/gtk/browser/main_window.py

By putting **every: day**, other-day or any valid date in the **quick add menu**, the task is set to recurring with a recurring_term being day, other-day,...
Furthermore, depending on the date on which the task has been set to done or dismiss, we calculate the next closest occurrence.
With this implementation, all subtasks of the recurring task are recurring.
When a recurring subtask is marked as done, its next occurrence will only appear after the parent has been set to done.
Further information:
When we first create a recurring task, there are some adjustments for calculating the date that we have to deal with. For instance,
the first time every: day adds 0 to the delta-time while in the next occurrences it adds 1. Also, the date parser calculates the date since the current date, …

Recurring/repeating tasks through the quickadd menu.

---

GTG/plugins/export/export.py
GTG/plugins/export/templates.py

Fix the file chooser, import the `GLib` library and convert to a bytes object when exporting because python wants a bytes object not an string.
Only tested with the "status" export.

Export plugin: Fix file chooser & exporting

---

GTG/gtk/backends/__init__.py
GTG/gtk/browser/delete_task.py

The latter would format the string first before translating, and having an translation for every possible combination is basically impossible.
I am using .format() specifically because diegogangl commented about having to drop it for .format(), so I am using that.
I tried to not modify the original string to not break existing translations, but I only was half-successful.
Fixes #380
Couldn't test the string about Synchronization Services because there aren't any (active) plugins for that.

Use _("...").format instead of _(f"...")

---

GTG/gtg.in
GTG/gtk/application.py
prefix-gtg.sh.in
scripts/debug.sh

Done a bit more than I would've liked, but it is a step closer to being DBus-Activatable (#183).
More testing appreciated. An current bug I've found is that when opening an task via cli (`gtg://....`), closing the task (and thus the application) and open GTG normally, it would reopen the task. I am not sure whenever this happens with the old implementation, but it might be worth investigating later.
I tried to explain in the commits, but there you go if you're lazy:
---
Use GLibs cli parser and use application.open
The primarily goal was to use the GApplication command line parser, so
that an user can also access gtk and GLibs command line arguments.
However, the opening tasks part made this much bigger, since it is done
from the activate-signal, which is usually reserved to open without …

Port commandline parsing to using GLib Application

---

GTG/gtg.in

I saw this being done in D-Feet:
https://gitlab.gnome.org/GNOME/d-feet/-/blob/b312c714fc01c3d14e2c6e1da6e87645674cca05/src/d-feet.in#L38-41
The problem is that some code uses gettext "at the module level", which is run when the module is being imported.
Before this change, basically all of GTG gets imported, before locale gets set up.
After this change, it gets setup before importing it, so it'll work as expected. Not sure why I haven't thought of this earlier.
I've put this in a if `__name__ == "__main__"` block, because the original code was also in such block.
Fixes #362
Fixes #378
Fixes #379
Haven't tested every string, but I did more of the for me easier tests and it works fine as expected.

Make module-level translations work

---

GTG/core/plugins/engine.py
GTG/core/timer.py
README.md

For #277
Yes, I figured the timer system bus signal not being executed thingy out. Finally!
See the commit message for more details:
> Initially, it didn't work. The reason was that system_dbus object is created on that line and when it goes out of scope, it gets destroyed and the signals get disconnected.
> 
> I assumed that the connection would stay open as part of Gio and not be created on first use (althrough it makes sense when implementing it). Also, I assumed that the signal would make it stay connected.
> 
> This took days to figure out, I even wrote a more "minimal" python version, and even a C version which let me find out the issue. See https://gitlab.gnome.org/-/snippets/1288
> 
> Thus the fix is to just keep a reference to it in the timer object itself.

Migrate Timer from dbus-python to Gio & drop dbus-python

---

GTG/gtk/browser/cell_renderer_tags.py

Previously, when getting an icon error while rendering tasks (such as when the user changes icon themes), it won't find the icon and prints an error.
This is fine, but it spams the terminal/console/logs with essential useless stuff, thus it is made sure only to print it once (per renderer).
I know about that possibly being dropped (see #85), but while it happens, I'd like to make it less spammy for me.

Don't print errors for the same icon multiple times

---

GTG/gtk/application.py
data/meson.build
data/org.gnome.GTG.desktop.in.in
data/org.gnome.GTG.service.in
meson.build

Previously, a bit of stuff was done in the constructor, which (likely) hurts being D-Bus activate-able, since the "remote" instance (aka when trying to execute GTG again which then would hand off to the existing instance) would re-initialize only to not use that stuff.
Also changed from using an list-comprehension `[x for y in z]` to an "normal" for-loop, since it is two lines anyway and the result isn't used.
~~One step closer to being DBus-Activatable (#183).~~
Edit: Now also fixes #183

Move from application constructor to starup signal

---

GTG/core/plugins/engine.py
GTG/plugins/export.gtg-plugin
GTG/plugins/export.gtg-plugin.desktop
GTG/plugins/hamster.gtg-plugin
GTG/plugins/hamster.gtg-plugin.desktop
GTG/plugins/meson.build
GTG/plugins/send-email.gtg-plugin
GTG/plugins/send-email.gtg-plugin.desktop
GTG/plugins/unmaintained/bugzilla.gtg-plugin
GTG/plugins/unmaintained/geolocalized-tasks.gtg-plugin
GTG/plugins/unmaintained/notification-area.gtg-plugin
GTG/plugins/unmaintained/tomboy.gtg-plugin
GTG/plugins/untouched-tasks.gtg-plugin.desktop
GTG/plugins/urgency-color.gtg-plugin
GTG/plugins/urgency-color.gtg-plugin.desktop
po/POTFILES.in
po/POTFILES.skip
po/meson.build

Make the `.gtg-plugin` files use the [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys), so that  [GLib Key-value file parser](https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html) can be used to pull localized strings.
It technically breaks the format since the GLib parser doesn't support most of pythons ConfigParser features.
This is unfortunate, but this was the easiest way to get this working, especially with gettext integration.
The probably biggest hack would be introducing `.gtg-plugin.desktop` files, which are just used so that xgettext (which is run by `ninja gtg-pot`) uses the Desktop-language on them, so the appear in the .pot and .po files correctly.
A current issue is that …

Translatable plugin file (.gtg-plugin) strings

---

GTG/gtk/browser/treeview_factory.py

this is super small change, but in my ubuntu I haven't installed or changing the default fonts, 
and using `\u2B6E` I'm seeing this:
so I try another similar unicode code `\u21BB` and it works for me
what do you think @diegogangl @zeddo123

using another unicode for recurring tasks.

---

GTG/core/dates.py

I was looking through the code and found that the offsets where not correct for `every other day` and `every month`.

Fix wrong offsets for recurring tasks

---

GTG/gtk/data/task_editor.ui

I don't know where they are used, but they appear in the translations, so better give them proper titles.

Better recurring popover titles

---

docs/contributors/translating.md

See commit messages
The plugin workaround is already known, see #457, not entirely sure why this is happening. (I would think it uses the symlink last updated which doesn't update when the file it points to updates)

Update translation doc (with plugins and additional option)

---

meson.build

Because I was getting the following warning:
WARNING: Project targeting '>= 0.50.0' but tried to use feature introduced in '0.51.0': args arg in i18n.merge_file
Because I used the args argument in #457 to set what keys gettext should translate.

Update meson to 0.51.0

---

GTG/core/dates.py
GTG/core/search.py
GTG/core/task.py
GTG/gtk/browser/treeview_factory.py
GTG/gtk/editor/editor.py
GTG/gtk/editor/recurring_menu.py

To better signify what those strings and their restrictions are.
In `GTG/core/task.py` I had outsourced 2 lists to an new variable so it isn't that crammed in there to make "proper" comments.
Shouldn't make any functionality changes.

Add translator notes primarily around parsing code

---

GTG/core/dates.py

There is no variable called "date" here.
Should fix #505. My fault introduced in #501, but didn't tested this fix.

GTG/core/dates.py: Use the correct date to cache

---

GTG/gtg.in

AFAIK doesn't really change anything, but [the return value should be used as an exit value from the documentation](https://developer.gnome.org/gio/2.64/GApplication.html#g-application-run).

Actually exit with the correct exit code

---

GTG/gtk/data/context_menus.ui

the logic was working and for example shortcut works, but the menu was disabled.
here we enable the logic for closed tasks.
close #405

Show as enabled delete context menu in closed task

---

scripts/debug.sh

See commits for more info. Makes it a bit more user friendly. Mostly aimed to fix #518 without having to remove the `.local_build` folder manually as a "workaround".

Some debug.sh fixes: Rerun meson with no build files, error handling and $PWD

---

GTG/core/info.py.in
GTG/core/meson.build

This is my attempt to fix #503 .
Use the output of "git describe --dirty" as the version string.
The info is filled in by meson.
I'm not sure if I'm happy about it because the version is now always taken from git describe.
Maybe the commit id should be somewhere else?

Include the git commit id in the version string

---

GTG/gtk/application.py
GTG/gtk/browser/main_window.py
GTG/gtk/data/context_menus.ui

This PR implements the feature discussed in #516 by @nekohayo.
Anytime the user uses the shortcut or the context menu, add new parent task will be added to the selected task _(switch parents if necessary)_ and a task editor will be opened.
I have also chosen the keyboard shortcut of `<ctrl><shift>P`.
close #516

Ability to "Add a parent task" to a task

---

GTG/gtk/browser/main_window.py
GTG/gtk/browser/tag_editor.py

While working on pane switching optimization, forgot one instance of `apply_filter_on_panes` getting called in the tag editor. Renaming `_reapply_filter` to `apply_filter` (since called outside of base class, can't be a "private" method anymore).

Fixing switch pane optimization

---

GTG/plugins/meson.build
docs/contributors/translating.md

Because otherwise when updating translations, those new translations aren't applied until forced a rebuild.
This would also mean you don't need the plugin workaround anymore when I introduced it in #494.

meson: Always build plugin files for translation

---

po/meson.build

Otherwise it would just silently don't copy the plugin files, so no plugins would be available when using GTG.
Found by nekohayo, where the test machine didn't had gettext.
Couldn't really test whenever it works so please test if you have such environment.

meson: Require xgettext to build plugins

---

scripts/debug.sh

From https://docs.python.org/3/library/devmode.html
Introduced in Python 3.7
Basically enables warnings and other stuff that could be useful to look into, including deprecation warnings.
Also see #549; Does not really fix it since it doesn't set `G_ENABLE_DIAGNOSTIC=1`.

debug.sh: Introduce -p to enable python dev mode

---

scripts/debug.sh

Builds upon #561 (the `-p` argument), so merge that first.
Removed `-b` since it doesn't work and `--boot-test` doesn't really say anything.
Looks now like this:
```
Usage: $0 [-s dataset] [-t title] [-d] [-p] [-n] (-- args passed to gtg)
-s dataset     Use the dataset located in $PWD/tmp/<dataset>
-t title       Set a custom title/program name to use.
-d             Enable debug mode, basically enables debug logging
-p             Enable python 3.7+ debug mode, like deprecation warnings
Also see https://docs.python.org/3/library/devmode.html
-n             Just generate the build system, don't actually run gtg
-- args passed to gtg
These arguments are passed to the application as-is
Use -- --help to get help for the application
```

Better help message for debug.sh (& remove -b argument)

---

scripts/import_tasks_from_flatpak.sh

Correcting directory names to match upper case

 Correct paths in import script for the Flatpak version

---

GTG/core/datastore.py
GTG/core/treefactory.py
GTG/core/versioning.py
GTG/gtk/browser/tag_editor.py
GTG/gtk/browser/treeview_factory.py
docs/contributors/file format.md

In the current development version, the state of the nonworkview attribute of a tag was correctly saved in the data file(s). After a restart of the application, this attribute was reset / not read properly by the loader.
Apart from the renaming in the code, I also added the `nonworkview` field in the format documentation.
However, I am not sure, if the attribute name shouldn't rather be `nonactionable` for everything. If you'd rather name it like that, I can change it accordingly in all other places.

fix nonworkview/nonactionable attribute loading

---

po/POTFILES.in

Makes the description in the about dialog working.
Fixes #602, but you need to re-generate the translation.
It seems it once was translatable, since it is still in the german translation (`po/de.po`), but commented out, and a simple regeneration (not done here) should bring it back to life.

Add info.py.in to be translated to have their strings be translatable

---

scripts/debug.sh

This makes the icon in the about dialog and probably some other stuff working in the `launch.sh`-script (so *not* when installed, where it works correctly, just when run locally).
Before:
After:

scripts/debug.sh: Add install dir while running

---

scripts/debug.sh

Not specifying `-t` explicitly still uses the default generated development title, but now doing `-t ''` will not add the `--title` argument to GTG and just use the application default one.
Primarily made to being able to create screenshot(s) in the about window without having to manually figure out what the real "title" is without removing the `-t`-argument in the debug script itself.

debug.sh: Add default title when it is explicitly empty

---

GTG/core/task.py
GTG/core/xml.py
GTG/gtk/editor/recurring_menu.py

While testing recurring tasks, I experienced a bug that way related to the recurring term in the editor; the title (aka `Every: <term>`) was being generate from `datetime.today()` which means that if you set the task to repeat every week you would have `Every: Friday` (correct) but when you open GTG tomorrow you would have `Every: Saturday` (incorrect) displayed.
To fix it, I added a timestamp for recurring tasks that gets updated whenever the recurring term is updated.

Fix recurring term not displayed correctly in Editor

---

flatpak/org.gnome.GTG-stable.json
flatpak/org.gnome.GTG.json

The previous runtime "is no longer supported as of February 13, 2021."

Update the Flatpak runtime version to 40

---

GTG/core/urlregex.py
tests/core/test_urlregex.py

The urlregex to find urls in the text contained a pattern that also
matched [a space character before the url][1]. This part of the pattern
was removed completely.
[1]: #618

Exclude preceeding whitespace from urls in textview

---

GTG/gtk/data/task_editor.ui
GTG/gtk/editor/recurring_menu.py

Previously it'll always default to the same year and month, by removing
the attributes it defaults to being today.
In code, it is then updated to match the current recurring status when
applicable.
The monthly selection is now always using January since it has 31 days,
the max days in a month.
To make sure this detail isn't seen when going to the yearly calendar,
this is made hidden with an ugly loop, trying out the next possible
month.
Fixes #637. Yes, the code is just a mess.

Update recurring calendar to today or selected date

---

scripts/debug.sh

This would allow to easily run custom python modules such as profiling or even an debugger.
I needed to `cd` into the build directory, otherwise it wouldn't find the modules, since at least with `cProfile` and `profile` I get different module path configuration.
Also, since I am not quoting `$prefix_proc`, it could have strange behaviour when the user passes `;` or other "shell characters", but I couldn't find a better way to make an single string to be something more "safe".

debug.sh: Add -p prefix-prog for better control

---

GTG/backends/backend_signals.py
GTG/core/datastore.py
GTG/core/timer.py
GTG/gtk/browser/cell_renderer_tags.py
GTG/gtk/browser/main_window.py
GTG/gtk/browser/simple_color_selector.py
GTG/gtk/editor/calendar.py
GTG/gtk/editor/editor.py
GTG/gtk/editor/taskview.py
GTG/gtk/general_preferences.py
GTG/plugins/dev_console/buffer.py
GTG/plugins/export/templates.py
GTG/plugins/unmaintained/bugzilla/bugzilla.py
GTG/plugins/unmaintained/tomboy/tomboy.py

See commit messages for more info. I basically ran `./launch.sh -w` and fixed some of the DeprecationWarnings it came up. I didn't touch theme/colour related stuff yet.
I am unsure about the "Try to use .get_property instead of .get_font" commit (with the UnicodeError) if I am doing something wrong. A quick `print` tells me `font` is `Pango.FontDescription`, just like what the old `.get_font()` returns. I'd guess it is maybe a object lifetime problem?
Testing appreciated.

Squash some deprecations

---

GTG/gtg.in
README.md

Uses https://pypi.org/project/setproctitle/.
Made optional since it isn't necessary for the application itself and is basically a use-once thing.
Fixes #638. An icon is even displayed (although it is provided by a 3rd party theme here):
The only downside I can see is that it also overwrites the command line thing, so you can't see with what command line it has been started with.

Add optional setproctitle to set process title

---

tests/tools/test_dates.py

i would like to improve code coverage of GTG. i submit this small merge request to know if you're interested if i try to add more tests. I 've targeted a low level module (Date) easier for me to undertsand.

test parse_only_month_day_for_recurrency method

---

GTG/core/plugins/api.py
GTG/gtk/browser/main_window.py
GTG/plugins/gamify.gtg-plugin
GTG/plugins/gamify.gtg-plugin.desktop
GTG/plugins/gamify/__init__.py
GTG/plugins/gamify/gamify.py
GTG/plugins/gamify/meson.build
GTG/plugins/gamify/prefs.ui
GTG/plugins/meson.build
po/POTFILES.in

Hi,
I have implemented the three main feature that I think are most important for this kind of plugins.
1. Count the number of tasks done per day.
2. Count the number of days in which the user has completed the goal
3. Added a score and level.
* message and emoji are displayed depending on the number of tasks done.
* The scores are calculated depending on a tag
* if the task has `@hard` as a tag, the user receives +3 points.
* if the task has `@meduim` as a tag, the user receives +2 points.
* if the task has `@easy` as a tag, the user receives +1 point.
* Levels
* 100 Beginner
* 1000 Novice
* 2000 professional
* 4000 Expert
* 9000 Master
* 13000 Master II
* 19000 Grand Master
* 25000 Productivity Lord
For the moment, the user can only change one thing which is the goal number of tasks per …

Gamify, a plugin to gamify your GTG workflow

---

data/org.gnome.GTG.desktop.in.in

Using this because it is recommended by the following FAQ entry, and
the seems the most appropriately solution after looking at the KDE
heuristics.
https://userbase.kde.org/LatteDock/FAQ#My_launcher_and_its_window_are_not_associated_correctly_OR_my_launcher_is_using_a_low-resolution_icon.3F
https://invent.kde.org/plasma/plasma-workspace/-/blob/951587ffaeb4c687cd2dd4a74e434fde15b06da6/libtaskmanager/tasktools.cpp#L210
I used D-Feet to look why it works there, and it turns out it matches
on the Name= part, that we don't want to modify (which would be GTG
here).
It probably works on gnome because it uses the (GTK) Application ID:
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/a472657490892592ce34ad3bc095c013c0d75e56/src/shell-window-tracker.c#L426
Thus it seems StartupWMClass= is the …

Add StartupWMClass to make pinning on KDE working

---

GTG/gtk/application.py
GTG/gtk/browser/main_window.py

Because otherwise in at least KDE it will display the default one.
It uses the application id because you need one anyway for the desktop
file, and would show the development icon version appropriately.
Before: Look at after but all the Icons are "X"
After (in development mode): ![Screenshot of GTG with various window open and the development icon visible](https://user-images.githubusercontent.com/1196130/116792616-13f2f900-aac2-11eb-92b3-df1cea9979e8.png)

Use application ID as the window icon

---

GTG/gtk/browser/cell_renderer_tags.py

Antialiasing was disabled, so the corners of the color boxed weren't as
smooth. Additionally, the correct icons are now used and rendered.
Unfortunately not GTK4-ready, since there has been some changed around
rendering icons it seems.
Fixes #324

Render tag icons better on HiDPI

---

GTG/gtk/editor/calendar.py

Copied the code used in the tag editor.
Fixes #382
Unfortunately not GTK4-ready since handling of shortcuts etc. has been changed in GTK4.

ESC now closes calendar picker window

---

GTG/gtk/editor/taskview.py
GTG/plugins/unmaintained/tomboy/tomboy.py

Because GDK4 dropped new_for_display in favour of new_from_name, and it *might* have better cursor theme compatibility.
Also partially see #647 and the linked #621. Not sure if it fixes it.
Also fixed a small flicker in the 2nd commit, that is very small that I think is OK for that PR.

 Use Gdk.Cursor.new_from_name()

---

GTG/gtk/browser/main_window.py
GTG/gtk/data/main_window.ui

Because other applications like nautilus do something similar.
Also makes the code a bit cleaner because the synchronisation is done by
GObject rather than doing it ourselves.
The F9 shortcut still works. Note that the video shows a bit of an older version, the newest has put the checkbox to the right like other GTK applications.

Make sidebar in menu a toggle

---

GTG/gtk/data/main_window.ui

Scrollbar policy "Never" means that it'll let the widget expand, not
sure why it was inserted there.
The default value works as expected.
Fixes #669. Note that the columns aren't re-adjusted when the window is resized, it just allows you to scroll.
https://user-images.githubusercontent.com/1196130/117730588-db070280-b1ec-11eb-87e1-bcc1231266ec.mp4

Fix cut-off when you expand the columns too much

---

GTG/gtk/browser/__init__.py
GTG/gtk/browser/tag_editor.py
GTG/gtk/data/tag_editor.ui
GTG/gtk/meson.build

Based on a design I saw that diegogangl made.
I made some change (like a remove button), but I am not too happy.
Additionally, you now require to apply the changes manually rather than
it being done automatically to prevent some possibly weird bugs.
Maybe this can be changed later, but not now.
Rather than constructing it in code, it is now done via a .ui-file,
initially generated by glade.
Thus a lot of the tag editor window code was essentially remade. This
time, I used GObject properties to be able to connect them with the
widget appropriately.
Fixes #306
~~Based on #276, but not marking as being fixed for a possibly better design. However, this PR already lays the foundation, so hacking on it will be easier.~~
Fixes #276 since I've got feedback and iterations
I've noticed that …

New tag editor window

---

GTG/gtk/browser/tag_editor.py
GTG/gtk/data/tag_editor.ui

From: https://github.com/getting-things-gnome/gtg/pull/666#issuecomment-834890560
> I thought about using a template for this window, maybe it's something
> we can hack later? I think it would simplify the code quite a bit.
It does, diegogangl.
Note that most of the diff in the UI-file is some indentation change
since instead of separate objects, they are directly children of the
template window.

TagEditor: Use Gtk.Template for less boilerplate

---

GTG/gtk/browser/main_window.py
GTG/gtk/data/context_menus.ui

This is useful for when you want to reschedule future tasks to today, or bump forward overdue tasks to today.

Make setting due date today an option in context menu

---

GTG/gtk/browser/main_window.py

Fix #648 by adding shortcut Ctrl+B to set focus on sideBar
(same as previous PR but with correct identity. thanks to the maintainers)

grab focus on sidebar

---

GTG/gtk/browser/cell_renderer_tags.py

Hello, this is my first ever contribution to an open-source project, and the prospect of GTG seems very promising. I thought I'd start small with some code formatting cleanup and better self-documentation for readability.
If you have any suggestions, please let me know. I will be more than willing to adjust as necessary. Here's to my first contribution, hopefully! 🎉
The following errors and warnings according to PyCodeStyle have been fixed:
- E402 (import order)
- E261 (comment spacing)
- E303 (too many blank lines)
- W504 (line break after a binary operator)
- E222 (too many spaces after operator)
- E305 (expected 2 blank lines after class declaration)

Cleanup the Cell Renderer Codebase

---

GTG/gtk/general_preferences.py

Caused some confusion to think it could have something to do with some issue (like https://github.com/getting-things-gnome/gtg/pull/658#issuecomment-834830045), but it doesn't.
Thus demoted to a simple warning, which isn't shown by default (without `-d`).

Demote default editor font log error to a warning

---

GTG/gtg.in
GTG/gtk/application.py
GTG/gtk/errorhandler.py
GTG/gtk/meson.build
GTG/plugins/dev_console/buffer.py

Did a while ago, but currently paused but planned to continue somewhat soon. Just in case: This is still Work In Progress (WIP)!
Basically when an uncaught exceptions is being caught (either explicit via a decorator or implicit via a global hook), it'll then display an dialog window with the info and ask the user to report it.
Also, would be a good place to also have an popup when something fails during initialization (which previously would just be silent end error out later due to uninitialized attributes).
Some ideas thrown in:
* Keep an action log of the last x actions to be included
* Maybe also include x lines of logs
Related: #247 but unlikely to have (explicit) integration with such crash reporters, for now.
First shared in the (Matrix) chat, here some (now outdated) screenshots:

Error popup on uncaught exceptions

---

README.md

This is required for getting GTG to work, otherwhise the following error
would occur:
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
It seems that package is installed by gedit, which is a default
applictaion for GNOME, so during package testing it might be easy to
miss.
Since python3-gi-cairo depends on python3-cairo, I "replaced" that
dependency, so the line isn't getting too long.
Found out by #716
I actually haven't tested this, but according to the reporter it should work.
Also, I haven't looked at Fedora yet, and I am unsure how to call it in the textual dependency list (where we mention pycairo).

README: Install python3-gi-cairo for debian

---

GTG/core/xml.py

The recent date thing #597 also changed the file loading code to make the
date reading code more compact, but also accidentally also removed
reading the tasks status, so all tasks were considered Open after a
restart.
Fixes #718
Also, it seems to only rewrite tasks in the XML tree when the task has been changed? Seems this is the behaviour, so unless something else was changed in the tasks other than just closing them, they should automatically be closed when this PR is applied (since the state is still in the XML file).

Fix tasks losing status at restart

---

GTG/gtk/application.py

Fixes #721
Looks like this now:
```
$ LC_ALL=C ./launch.sh -- --help
[cut build system output]
Usage:
gtg [OPTION?] [gtg://TASK-ID?]
Help Options:
-h, --help                 Show help options
--help-all                 Show all help options
--help-gapplication        Show GApplication options
--help-gtk                 Show GTK+ Options
Application Options:
-v, --version              Show program version
-d, --debug                Enable debug output
-t, --title=TITLE          Use special title for windows' title
--display=DISPLAY          X display to use
```
For some reason, the special triple dots "…" displays as a question mark when using `LC_ALL=C`, but display correctly in my language (German UTF-8). Using `LC_ALL=C.UTF-8` just displays the German text for me.

Add gtg://TASK-ID to the command line help

---

GTG/gtk/browser/cell_renderer_tags.py

This blurs the pretty border and imo makes it look very smeared (and the shape looks weird too).
This definetely is better than having a low res rounded rectangle in
HIDPI though, so there it is still anti-aliased.
See https://github.com/getting-things-gnome/gtg/issues/727  (I first typod the issue number, this is why I mentioned the wrong issue)

cell_renderer_tags: don't antialias on lodpi

---

GTG/plugins/meson.build
docs/contributors/translating.md

Since meson 0.60, the `build_always_stale` option was removed:
https://github.com/mesonbuild/meson/commit/6b1a80024c79876dc3b75f2b525be24ca8fe671a
However, meson doesn't make such files depend on the translation .po
files, which is a known bug:
https://github.com/mesonbuild/meson/issues/2621
So with that option taken away, I tried passing a list to the input
which includes all .po files, since I saw it only uses the first element
for the translations, but that fails when trying to generate po files.
Since it seems you can't dynamically add dependencies after the fact,
this seems like a dead end, so I am reverting this for now to make it
compile on meson 0.60.
Reverts #555 to fix #720

Revert meson plugin translation apply thing

---

GTG/backends/backend_localfile.py
GTG/core/datastore.py
GTG/core/requester.py
GTG/core/tag.py
GTG/gtk/browser/tag_editor.py
GTG/plugins/export/export_templates/template_simple.html

Since unfortunately saved searches and tags share the same namespace, it
makes it difficult to create a saved search with the exact name as an
existing tag.
As a current workaround until we separate them, we just prefix the saved
searches with `SEARCH_TAG_PREFIX`, which an user is unlikely to use.
From what I can see, it still displays properly in the UI after some
fixes, aside from existing bugs, like the tag editor stripping spaces, `@blog !or @efficiency` having the first `@` stripped out in the sidebar, and so on.
In the XML file this prefix isn't added, because it would be redundant
and make it easier to deal with in future versions.
See for example #629. Does not fix tag inconsistencies (renaming, special symbols etc.).

Workaround: Separate saved searches with tags name

---

GTG/gtg.in
GTG/gtk/editor/editor.py
GTG/gtk/editor/taskview.py
README.md

This PR makes taskview sublcass GtkSource.view instead of the regular textview.
The immediate change is that now we can have undo/redo. It also opens the door for more features, like tag autocompletion.
It's a small enough change that can go into 0.6
The only limitation for now is that you can't undo a subtask once it's created. I don't think this is particularly bad though, since ctrl+z'ing a subtask would delete it without confirmation.
closes #296

Use GtkSource.view for taskview and enable undo

---

scripts/anonymize_task_file.py

Also, flatpak detection added because I can, but untested.
And anonymizes tags by using their ID.
And adds the task ID to the title so it is easier to identify them.
And saved searches, where the query is a constant value.
Fixes #733
Testing appreciated since I whipped this in like 30 minutes. Works for neko however.

Adjust anonymize task script to work with new file format

---

GTG/gtk/browser/main_window.py

Previously, when expanding a task (either by the user or by liblarch
itself, which itself tries to remember collapsed nodes and expand other
ones), GTG would for some reason visit all nodes again just to check
each node again, and expand nodes that should've been expanded.
This additionally has the problem when creating a new parent task but
you haven't visited the 'open' tab yet, then all nodes are collapsed
(which is the default of Gtk.TreeView). When adding a new parent task,
liblarch sees that a new first child node has been inserted into the
tree (probably used by TreeView to make them easier to whenever to
display the expand arrow thing), and since liblarch expands all nodes by
default, it expands it.
However, now the old handler then goes on and expands all tasks, but
each …

Make task expanding more efficent

---

GTG/gtk/browser/quick_add.py
tests/core/test_quickadd.py

Quick entering `Do a thing due:meh` causes GTG to completely freeze, and need to be killed. This fixes it to treat tokens with invalid dates the as other invalid tokens, ignoring them (and removing them from the input text).
This issue was caused since the the `continue` in the parsing loop didn't remove the token, causing it to loop forever on the invalid token.

Don't loop forever with invalid quick add date

---

GTG/gtk/application.py

This can be triggered when GTG first starts and there are no selected
tasks.
fixes #753

Prevent errors when no task is selected

---

GTG/gtk/backends/backendstree.py

We only import `rgb_to_hex` but not `rgba_to_hex`, but the latter is
being used.
It seems to work with RGBA, so we just use the RGBA version.
Fixes the following error message:
File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/backendstree.py", line 125, in on_backend_state_changed
color = rgba_to_hex(color)
NameError: name 'rgba_to_hex' is not defined
Fixes #755

GTK Backendtree: Use correct RGB to hex function

---

GTG/gtk/editor/editor.py

Saving makes sure the task has the correct title when being added as a
subtask to the new parent. Otherwise the title gets overwritten with the
default title.
fixes #745

Save task before creating parent

---

GTG/gtk/data/main_window.ui

Basically #665 but for that entry that (wrong) property was introduced in the CalDav changes it seems.

Make Synchronization menu entry keyboard selectable

---

GTG/gtk/browser/adaptive_button.py
GTG/gtk/browser/main_window.py
GTG/gtk/data/main_window.ui
GTG/gtk/meson.build

A bug report #673 was that the minimum width of the main window is a bit too
high for some resolutions (when trying to use GTG half of it). A
proposed solution #677 would be to use an icon, but it is rather hard to find
a good system-provided one.
What I've thought is that maybe just display the "Start tomorrow" text
while the window is big enough, and only the icon when it gets smaller.
I couldn't find a good way to do that with only using GTK stuff, so I
whipped my own (and first) widget that displays an widget depending on
the (minimum) size of its children widgets, which then would be the
"Start tomorrow" label, and an Image for the icon.
This widget is rather tailored for GTG in that usecase only, which means
not everything has been implemented yet, like different size request
modes. …

Adaptive tomorrow button to make window smaller

---

GTG/core/xml.py

Previously, an task not using recurring GTG would write
<updated_date/>
but v0.5 tries to parse the text which doesn't exists and thus errors:
Traceback (most recent call last):
File ".local_build/install/lib/python3.8/site-packages/GTG/gtk/application.py", line 97, in do_startup
datastore.register_backend(backend_dic)
File ".local_build/install/lib/python3.8/site-packages/GTG/core/datastore.py", line 463, in register_backend
source.start_get_tasks()
File ".local_build/install/lib/python3.8/site-packages/GTG/core/datastore.py", line 700, in start_get_tasks
self.backend.start_get_tasks()
File ".local_build/install/lib/python3.8/site-packages/GTG/backends/backend_localfile.py", line 185, in start_get_tasks
task = xml.task_from_element(task, element)
File …

Make unused recurring task work with v0.5

---

NEWS

I added in the updates from the Gdoc. I put it in similar categories as was done for the previous releases. I went a little more in-depth than 1 line for some of the new features since I wasn't sure if we were also going to have a blog post. 
The only one that I didn't include was `Fixed several nekobugs [expand]` because I wasn't really sure what that meant. If you want me to add something for that, I can. I also want to make sure `Fixed the bug where every editor window would pop back if GTG wasn’t closed cleanly (ie, shutting down the pc)` was true because there was a comment on the Gdoc questioning it. 
Let me know if you would like any other changes.

Update NEWS for 0.6

---

GTG/gtk/browser/quick_add.py

Also switch to a for loop for matches, this prevents the while loop from
accidentally going infinite.
Also don't add tags if they are empty. For instance, "tags:some,other,,"
would have added two empty tags at the end (single @s).
Also use replace to remove text instead of slicing (more reliable)
fixes #771

Only remove recognized tokens in quick add

---

GTG/gtk/editor/calendar.py

Fixes the "Pick a date" button next to the Tomorrow button dropdown
menu, or inside the menu when you right click on a task.
Traceback (most recent call last):
File "GTG/gtk/browser/main_window.py", line 1216, in on_set_due_for_specific_date
self.calendar.set_date(date, GTGCalendar.DATE_KIND_DUE)
File "GTG/gtk/editor/calendar.py", line 79, in set_date
self.__calendar.select_day(date.day)
AttributeError: 'Date' object has no attribute 'day'
Fixes #779, broken by the Date class rewrite. Using grep I tried to look for other places we missed to convert, but it seems this was the only location we overlooked.

Fix exception when trying to use calendar widget

---

GTG/gtk/browser/adaptive_button.py

For some reason when using gnome-shell and maximizing GTG the widget
will be offset (just enough you can still see part of it outside the
button).
After reading more code it seems we need to resize the Gdk.Window when
doing size_allocation (which some of the GTK code doesn't do because it
was hidden behind some CSS helper functions it seems). We just call the
Gtk.Widget.do_size_allocation because they do it already for us.
Fixes #785

Fix adaptive widget offset when maximized in gnome

---

GTG/gtk/browser/main_window.py
GTG/gtk/data/context_menus.ui
GTG/gtk/data/main_window.ui

This is an attempt at resolving some of the consistency problems presented in issue #550.
It doesn't solve them _100%_ because I couldn't find a way to access the individual menu items in the right-click menus like you can with GtkPopover's menu button widget IDs, so I got stumped by that. I tried some things but they didn't work and they also looked like nasty hacks. If you have ideas/suggestions of how to achieve that easily (or maybe it's just possible in GTK4, if the menus changed there?...) I'd be happy to try them, but I think I've run out of patience for now. The existing changes should already be a noticeable improvement, and maybe someone else can come in to fix the remaining part (right-click menus) on top afterwards.
I have tested this to be working both in English and my …

Harmonize the headerbar's task deferral popover menubutton labels with the right-click menus'

---

GTG/core/xml.py

Fixes #796
Caused by 3ab87019ab7d163aeb91db4728f95ef2424d8a23
Reproduction steps: `./launch -s completelynew`

Fix crash when creating new profile in xml.py

---

docs/contributors/translating.md

Fixes #802
Markdown rendered preview at https://github.com/Neui/gtg/blob/translating.md-mention-errorhandler/docs/contributors/translating.md#testing-error-handler-dialog

translating.md: Add error handler dialog for testing

---

GTG/plugins/export/export.py
GTG/plugins/hamster/hamster.py
GTG/plugins/send_email/sendEmail.py
GTG/plugins/untouched_tasks/untouchedTasks.py

It seems using Gtk.ModelButton.set_label() inserts a label widget, but
Gtk.ModelButton.props.text also adds a Gtk.Box around the label.
The first method makes the label centered, which looks out of place with
the other menu entries, but the latter does not. So just switch it out
to maintain consistency.
Interestingly, the dev console already uses the `text` property, so it
wasn't affected since it was already doing it correctly.
Fixes #800

Fix menu button alignment from plugins

---

po/POTFILES.in

I used the following command to find out some of the files:
diff -u \
<(sort po/POTFILES.in | egrep -v '\.ui|\.desktop') \
<(grep -r '[^_]_(' GTG --files-with-matches --include='*.py' | sort) | xclip -in -selection clipboard
Fixes #799, at least they show up (but haven't checked whenever they also really are applied, just took a look at `po/gtg.pot` after `ninja -C .local_build/ gtg-pot gtg-update-po`)

Add new files to POTFILES.in for translation

---

po/pl.po

Adding missing translator credits in Polish and cleaning language team e-mail (there's no such thing).

Fix missing translator in pl

---

GTG/gtk/editor/taskview.py

Fixes #807
Allows dots only to be used only inside tags, but not at the end, so tags can be clearly used in sentences like:
> will also appear when you select `@money`.
> I wish I have more `@time`...

Skip ending dots in tags

---

GTG/plugins/send_email/sendEmail.py

Closing part of  #821
Allows to export task content via e-mail.

E-mail plugin content fix

---

GTG/plugins/export/export_templates/script_pocketmod

Fixes #831
Converting old wrapper scripts `pdf90` and `pdfnup` directly to `pdfjam`.
It works for me with default first-run task list, but please test with much more tasks, at least to fill the whole 8 pages.

Fixing export plugin PDF template

---

GTG/plugins/export/export_templates/script_pocketmod
GTG/plugins/export/export_templates/template_pocketmod.tex

This commit completes the fix for #831 - follow up from #833.
Also dropping German language specific TeX option.

Fixing PDF export plugin

---

GTG/plugins/untouched_tasks/untouchedTasks.py

Untouched tasks plugin adds `@untouched` tag with `@` included in the name, which confuses GTG - each task opening adds another copy of this tag. Skipping this character fixes the problem.

Fixing @untouched tag problems

---

GTG/gtk/editor/editor.py

Fixes https://github.com/getting-things-gnome/gtg/issues/825
This patch hides all the special tags (including saved searches) from the tag popup in task editor.

Hide special tags in task editor popup

---

GTG/gtk/browser/main_window.py

Fixes https://github.com/getting-things-gnome/gtg/issues/684
Removes unneeded condition line that checks if tag name includes `@` character. Actual tag names are chains that follow this character, it only acts as an indicator that the tag name starts here.

Prefill new task with selected tags

---

snap/snapcraft.yaml

Add Snap support
The Snap uses metadata from AppData, so it always gets the latest version, summary, description and so on, so no need to edit the file each new release.
The version of liblarch is hard-coded.
To generate the .snap file, you just have to clone the repository with my PR in it and execute `snapcraft` command in the project root directory.
The last remain question about the support is how to publish in the Snap Store in an official way, similarly to how Flatpak is published.
Please help me to test. I don't have a CalDAV server to test CalDAV backend, for instance. I allowed network communication so I think it will be enough.
Closes #872

Add Snap support

---

GTG/plugins/send_email/sendEmail.py

Fixes part of https://github.com/getting-things-gnome/gtg/issues/821
Subtask list formatting:
- if there are any tasks, put a dash character before each of them - instead of skipping it for the first subtask
- if there are none, print nothing - instead of an empty line
Translation regeneration required.

Correct subtasks formatting in e-mail plugin

---

GTG/backends/backend_caldav.py

Since CalDav sync is still very wonky and in fact deleted all of my tasks (luckily I managed to restore all of them) I decided to only connect GTG to shared calendar and log with separate account (very easy to set up in Nextcloud).
The problem that I noticed was, that for shared calendars the identifying tag would be of format `@DAV_NAME_(user)` and with every sync the part `(user)` would be multiplied to the next line effecting in absolute madness of a spam at the top of every task.
This should fix the issue.

Fix collaborative calendar tags

---

GTG/gtk/browser/delete_tag.py

Makes clear that only the tag is deleted, no tasks
Closes https://github.com/getting-things-gnome/gtg/issues/835

GTK/gtk/browser/delete_tag.py: Small language improvement

---

GTG/core/config.py

Left panel seems to be important tool for managing tags, so I think it should be open by default. 
It's especially important for the first time users to see it. Opening panel is described in the initial guiding tasks, but let's make it as easy as possible to discover this important feature, even without getting through the guide.
Current initial state looks like this:

Open tag panel by default

---

GTG/core/xml.py

Fixes https://github.com/getting-things-gnome/gtg/issues/851
When reading from file, there are multiple actions which are changing task modification date (like `set_date()` with other keys or `set_recurring()`). Therefore setting modification time needs to be the last action to not be overridden with current time. We don't want to treat mere initialization process as real task modification.
It affects untouched tasks plugin in the obvious way - it gets current time as task modification time, so it can't recognize forgotten ones. It may also affect other actions relying on modification time (maybe synchronization).

Keep modified date when reading from file

---

GTG/core/firstrun_tasks.py

Fixes https://github.com/getting-things-gnome/gtg/issues/803
Replaces initial static tags with dynamic ones, collected from localized task content. This allows proper tags translation.
Since `&quot;@waitingfor&quot;` string is not matched by `extract_tags_from_text()`, `&quot;` part has been dropped. Because of that regenerating POT file (and translations) is needed.

Dynamic tags in the first run

---

GTG/core/base_store.py
GTG/core/datastore2.py
GTG/core/tasks2.py
GTG/gtk/application.py
GTG/gtk/browser/delete_tag.py
GTG/gtk/browser/main_window.py
GTG/gtk/browser/modify_tags.py
GTG/gtk/editor/editor.py
GTG/gtk/editor/taskview.py
tests/core/test_task2.py

Another preparation step for a larger branch. This PR plugs the new core into the actual app. 
The new core works alongside the old one, it reads the `gtg_data.xml` file but saves to `gtg_data2.xml`. This lets us verify that both cores are producing the same files (or at least similar enough).
This PR also includes a few bug fixes and improvements to the core.
There's still _a lot_ to do, but this pull is a solid stepping stone. No changes in here are visible to users.
For now on, the new datastore can be accessed through `app.ds` in the developer console.

Plug new core

---

GTG/core/config.py
GTG/gtk/errorhandler.py

Fixes trying to store values which contains a percent sign (%).
For example, for some reason Task IDs could contain those and this would
throw an error when trying to assign to the configuration value for
currently opened tasks.
Also done for errorhandler reading flatpak info just in case.
See https://docs.python.org/3/library/configparser.html#interpolation-of-values
Fixes #914

Disable config parser interpolation

---

README.md
meson.build

Technically not required, but typically desired so passwords work (such as when using CalDav backend).
Fixes #902

Add libsecret to dependencies readme

---

po/fr.po

The "actionable" view is named "actionnables" in french, this PR updates the french translation accordingly

Fix typo "actionable" in french translation

---

GTG/plugins/untouched_tasks/untouchedTasks.py

Fixes #926 .  Fixes #912 .
Changes `today` in `untouchedTasks.add_untouched_tag()` to be a `datetime.date` instead of a `datetime.datetime`, making the comparison at line 114 (which was previously throwing an exception) valid.

Fix fatal error in untouched tasks plugin

---

GTG/backends/backend_localfile.py
GTG/core/versioning.py

This is my proposed fix for the incompatibility between `scripts/import_tasks_from_local.sh` and the versioning decisions in `versioning.py` and `backend_localfile.py`.
Fixes #920 (hopefully).

Proposed (works for me) fix of versioning detection

---

docs/gtg.1

This pull request changes unknown macro .bu to valid groff syntax for bullet lists.
From the downstream debian package:
https://salsa.debian.org/python-team/packages/gtg/-/blob/debian/master/debian/patches/fix_man_page_bullet_list.patch

Unknown macro .bu in man page

---

GTG/plugins/export/export_templates/script_pocketmod

The export script `GTG/plugins/export/export_templates/script_pocketmod` does not quote the input parameter `SOURCEFILE` which make it fails with spaces in this path.
This pull request adds quotes when reading the input argument and when using the variable as command argument.
Patch from the Debian package team:
https://salsa.debian.org/python-team/packages/gtg/-/blob/debian/master/debian/patches/quote_source_file_in_script_pocketmod.patch

Quote SOURCEFILE in script_pocketmod to handle spaces in path

---

GTG/core/base_store.py
GTG/gtk/editor/taskview.py

https://github.com/getting-things-gnome/gtg/actions/runs/3289608770/jobs/5421351329#step:5:39
=============================== warnings summary =============================== tests/core/test_saved_search.py::TestSavedSearch::test_add_simple
/home/runner/work/gtg/gtg/GTG/core/base_store.py:62: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
log.warn('Failed to add item with id %s, already added!',
tests/core/test_saved_search.py::TestSavedSearch::test_new_tree
/home/runner/work/gtg/gtg/GTG/core/base_store.py:73: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
log.warn(('Failed to add item with id %s to parent %s, '
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ======================= 169 passed, 2 warnings in …

Fix deprecation warnings showing during testing

---

.github/workflows/unit_tests.yml
README.md
flatpak/python3-requirements-dev.yaml
flatpak/requirements-dev.txt
tests/backend/backend_caldav_test.py
tests/core/test_config.py
tests/core/test_timer.py
tests/test_utils.py

It was moved to the stdlib in python 3.3, and the PyPI version is a backport for python versions less than 3.3.

migrate from external mock package to stdlib unittest.mock

---

GTG/gtk/editor/taskview.py

Fixes #987
After replacing string `\B` with `(?<!\/|\w)` addresses like https://wikis.world/@announcements (@ inside URL) are not treated as tags any more.

Tag regex refinement

---

GTG/core/saved_searches.py

Fixes 1. problem from #1044
Saves search only if this name (=query) is not already saved to avoid duplicate searches.

Check if search is already saved to avoid duplicates 

---

GTG/core/meson.build

This explicitly checks the command before assigning to the `version` variable.
This also addresses the following warning during building:
```
WARNING: You should add the boolean check kwarg to the run_command call.
It currently defaults to false,
but it will default to true in future releases of meson.
See also: https://github.com/mesonbuild/meson/issues/9300
```

Append short commit hash in development profile 

---

GTG/gtk/editor/editor.py
GTG/gtk/editor/taskview.py

This fixes issue #605 (as promised in #1058).
- It solves the problem by masking out the currently edited word to prevent parsing half-typed tags. 
- It also ensures to parse everything when closing the window. 
- (Note that this does not eliminate already existing partial tags in the `gtg_data.xml`.)

Prevent parsing the current word as a tag when editing a task

---

GTG/core/tasks.py

Since the default value for `UUID` is `None`, we can safely avoid unnecessarily checking if `UUID` exists.

Add parent to `self.add`

---

GTG/core/datastore.py
GTG/core/tags.py
GTG/gtk/browser/sidebar.py

Hi!
I am a newcomer. This PR fixes issue #404 .
Parent tag's task count was not updated when adding/removing children tags to them.
The problem is solved by overriding the `set_parent` method in the `Tag` class and introducing a `_get_ancestors`  helper method.

Properly maintain the task count in Tag.set_parent (fix #404)

---

GTG/gtg.in
meson.build
pyproject.toml
tests/conftest.py

This lets us run tests using the build system.
It also makes GNOME Builder display the test in its tests list so we can execute them from there.

Register pytest test with meson

---

.gitignore
GTG/gtk/browser/main_window.py
GTG/gtk/editor/editor.py

Fixes #1039
Updating the start date of a task may influence whether or not it needs to be visible. For example, if you're on the Actionable pane and you set the start date of a task to some time in the future, then the task is no longer actionable and needs to disappear from that view.
Testing by having some tasks in the Actionable pane, then verifying that the following make the task disappear from the pane:
* click on a task and then on Start Tomorrow
* right-click on a task > Set Start Date > "anything in the future"
* double-click on a task > modify "Starts on" to a date in the future > close task editor
* create a new task > without closing the editor, add a child to it > click on child > click on Open Parent

Update the pane's filter when updating the start date of a task

---

.gitignore

I do my dev work using virtual environments, like venv/ or venv38/ to test different versions of Python.
This removes them and the many files they contain, from git.

Add standard Python virtualenv names to gitignore

---

GTG/core/tasks.py

Fixes #1058
1. During tag renaming, a simple `str.replace()` was used, which led to unexpected behavior. This PR uses `re.sub()` that considers some special cases (e.g., a tag is a prefix of another, email addresses, etc.) One can use the following input to quickly check the solution. (Only the first two lines should be modified when renaming `@xxxx`.)
```
aaaa @xxxx bbbb
@xxxx
aaaa@xxxx.yy
a @xxxxbbbb
a a@xxxx a
@xxxx-aaaa
@xxxx_bbbb
xxxx
```
2. I noticed that similar problems are present during tag removal. These are also fixed. You can exercise the functionality by using the following input and removing `@vvvv`:
```
@vvvv
aaaa bbbb cccc dddd
@aaaa, @vvvv, @bbbb, @vvvv-cccc
aaaa @vvvv cccc
aaaa@vvvv.bb
```

Use re.sub() instead of str.replace() for tag renaming and removal.

---

GTG/core/tasks.py

Fixes #1029
When unparenting a task, inline references of the old subtask must be removed from the old parent's content.
(Otherwise, the reference is parsed again and removed unsuccessfully, causing the crash described in the issue.)

Remove inline references when unparenting a task

---

README.md

Building GTG from source also requires gtksourceview4-devel, so I added it here

Fixed missing build dependancy for Fedora

---

GTG/gtk/editor/editor.py

Fixes #1026
The crash happened because the program tried to delete the same unmodified new task twice. After hitting `Escape`, the `TaskEditor`'s `close` method was called. This override called `self.destruction()`, thus deleting the new task. After that, `super().close()` was also called emitting a `close-request` signal. This `close-request` signal was also [connected](https://github.com/getting-things-gnome/gtg/blob/b2dec14ca98db5453bd74ca524ded6d0a0a8bc3e/GTG/gtk/editor/editor.py#L241) to the `destruction` method, thus trying to delete the same task the second time.
The `TaskEditor`'s `close()` override is now removed. Its only function was to call the `destruction()` method. However, the `destruction()` method was already connected to the `close-request` signal.

Avoid deleting an unedited new task twice

---

README.md

Update build status badge to use the github workflow and move it more towards the top.

readme: Remove outdated and obsolete build status badge

---

GTG/gtk/browser/main_window.py
GTG/gtk/editor/editor.py

Fixes #1075 
It seems that `main_window.py` still has a significant amount of GTK3 code. For example, `self.req` is mentioned a lot in `main_window.py`, but `MainWindow` doesn't have that attribute.
Once concerning thing is that now, when setting a Start Date or Due date via `Right click on a task > Set Start Date > Pick a Date`, GTK logs a warning:
```
(gtg:27345): Gtk-WARNING **: 18:22:45.883: Broken accounting of active state for widget 0x223b9e0(GtkWindow)
```
I didn't dig into that.

Fix AttributeError when setting start date

---

GTG/gtk/editor/editor.py

Fixes  #1055
When you create a new task, the default title is selected so that when you start typing, you write the title of the task.

Highlight title when creating a new task

---

GTG/core/tasks.py

This fixes the test suite again, which fixes #1053
I think #1036 was merged without rebasing, and https://github.com/getting-things-gnome/gtg/commit/4ed9bc88067d5efdb48d4e262e7e6a7872095c9c was committed in between and [broke a test](https://github.com/getting-things-gnome/gtg/actions/runs/8512039052/job/23312837322):
```
>       parent.content = re.sub(r'\{\!\s*'+item_id+'\s*\!\}','',parent.content)
E       TypeError: can only concatenate str (not "UUID") to str
```
I'm not entirely sure how this line was supposed to work, given that item_id's type hint is UUID and there is no `+` operation between UUID and str. I'm guessing a caller was passing a string? I didn't manage to trigger the TypeError from the GUI.
But even if the type hint is wrong and a string can be passed, running `str()` …

Fix TypeError when unparenting

---

GTG/core/tasks.py

pytest with Python 3.11 shows `DeprecationWarning: invalid escape sequence '\s'`. Use a raw string to fix this.

Fix deprecation warning

---

.github/workflows/unit_tests.yml
GTG/__init__.py
GTG/core/info.py.in
GTG/core/meson.build
GTG/core/system_info.py
GTG/gtk/browser/main_window.py
GTG/gtk/errorhandler.py
build-aux/org.gnome.GTG.Devel.json

This makes a few changes and additions:
- This adds a new dependency on libportal. It's used to detect if it's sandboxed.
- Various `GtkButton`s are added to provide external links.
- The Credits section has been reworked to prevent the about dialog from increasing.
- New System section was added to help users copy and paste system information for troubleshooting purposes.
- The about dialog is now a modal window.
Screenshots:
| About | System |
|--------|--------|
| ![image](https://github.com/getting-things-gnome/gtg/assets/50847364/ae9afd21-33a2-4d3c-84ff-b6c914c27ff4) | ![image](https://github.com/getting-things-gnome/gtg/assets/50847364/00f00c95-3160-497c-9e71-ef6a289478e8) |

Rework About dialog

---

GTG/gtk/editor/editor.py

This allows checking at a glance if the current task blocks a project:
Fixes https://github.com/getting-things-gnome/gtg/issues/1027
---
Potentially, I could maybe also add another commit on top that recursively counts how many parent levels there are, and adds an extra line to say something like:
> In total, %d parent tasks are blocked by the current task.
…what do you think, would that extra info be helpful too, or too much?

Show parent's title & children count in "Open Parent" button tooltip

---

GTG/core/tasks.py
GTG/gtk/browser/quick_add.py
tests/core/test_task.py

Fixes #1068
In some cases, `None` was used instead of `Date.no_date()`, which caused a crash when sorting the task list. These changes follow the already existing type hints and comments.

Use Date.no_date() instead of None for Task.date_due

---

GTG/core/tags.py
GTG/gtk/browser/sidebar.py
GTG/gtk/browser/task_pane.py
GTG/gtk/data/style.css

Fixes #1042
The new code leverages `GtkTreeExpander`'s ability to handle indentation both for tags in the sidebar and tasks in the task list. I also created a `children_count` property for the Tag class so that the expander can bind to it.

Fix alignment in hierarchical views

---

Makefile

Running tests locally has become a bit more involved recently. We can keep them out of "make check" for now, so that we can at least get some basic style checks running again.
Fixes #838
(actually the error in that issue was fixed with the new core, but there was a new error related to `run-tests`)

Remove tests from checks

---

.github/workflows/unit_tests.yml
.pre-commit-config.yaml
README.md

Relates to #237
This adds a simple configuration for [pre-commit](https://pre-commit.com) and runs it on GHA. It doesn't do very much; mostly removing trailing whitespaces.
My next step would be to add pylint or pyflakes to this, and tell it to ignore every warning that GTG currently breaks. This would:
* prevent us from breaking any more
* allow us to fix the warnings one at a time, when we can
I tested the GHA on a fork.
This commit doesn't contain the changes that fix the pre-commit check, so GHA will fail. To fix it, we'll just need to run `pre-commit run --all-files` and commit the result.

Add simple pre-commit hook

---

GTG/core/tasks.py
GTG/gtk/browser/task_pane.py

This fixes one of the problems listed in GitHub issue #1018:
> If you drag a child from one parent to another task (re-parent), it duplicates it in the view
- The `tid_to_subtask_model` field keeps track of the `ListStore`s created for subtasks. 
- The `_remove_from_parent_model` and `_append_to_model` helper functions update these models when a change happens. 
- Thanks to this new functionality, some GUI updates are simplified.

Update models for subtasks upon changes

---

GTG/gtk/browser/task_pane.py

The index 0 was getting cast as false in the if-clause so select_item was never getting called. Good old duck typing shenanigans.
Fixes #1008

Fix RMB menu for first task

---

GTG/gtk/browser/main_window.py

This might throw a warning the first time since the config was using the old names for the panes/views.
fixes #1019

Restore the selected pane saved in config

---

GTG/core/tasks.py
tests/core/test_task.py

If the content had some whitespace the if-guard would fail, creating a tooltip with just "...".
It would also fail because it would include tags and subtasks. So now we first process the content properly and then check.
Also fixes the regex to remove tags in a comma list properly from the excerpt
fixes #1010

Fix check for empty excerpts in popups

---

GTG/gtk/browser/main_window.py

In file: main_window.py, the comparison of Collection length creates a logical short circuit. I suggested that the Collection length comparison should be done without creating a logical short circuit. 
Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed – to improve global software supply chain security.
The bug is found by running the Intelligent Code Repair (iCR) tool by OpenRefactory and then manually triaging the results.

Fix an inappropriate test expression to remove a logical short circuit

---

GTG/gtk/browser/sidebar.py
GTG/gtk/data/style.css

Fixes #1017 and the following points of #1018:
> - If you drag a child out of a parent, the selected tag in the sidebar resets to "All Tasks" view
> - If you drag a standalone task into a parent (turning the task into a child), the selected tag in the sidebar resets to "All Tasks" view
Based on [a forum discussion](https://discourse.gnome.org/t/list-box-first-row-is-always-selected/14840/2), if the currently focused widget is removed, Gtk.Window selects the first suitable children. This is the "All Tasks" row in our case, thus causing a view reset. Other cases can also reproduce the anomaly: reparenting a tag, deleting a task, etc.
Now, an invisible button catches the focus instead of the "All Tasks" row. Thanks to this button, unintended view resets can be avoided when the focused widget …

Create a dummy button in the sidebar

---

GTG/core/filters.py

The removed return statement prevented the inclusion of certain tags if there was a previous sibling with children.
(As far as I know, there is no open issue for this bug.)

Fix tag expansion in TaskPaneFilter

---

GTG/core/tags.py

The original XML export for tags looped over only the root elements when collecting parent-child relations. Now, the code uses the `lookup` dictionary containing every tag.
As far as I know, there is no open issue for this bug.
**Detailed steps to reproduce the bug:** 
1. Create a deep tag structure with four levels.
```
- a
- b
- c
- d
```
2. Close the program.
3. You can already see the faulty export in the `gtg_data.xml` file.
```
<taglist>
<tag id="e21eac43-35d2-480e-8818-5b86dc48b20d" name="a" nonactionable="False"/>
<tag id="b5a629bc-b146-42b8-a6d0-26a651285d7b" name="b" nonactionable="False" parent="e21eac43-35d2-480e-8818-5b86dc48b20d"/>
<tag id="cece686c-607d-4388-9bd1-11560d8b32ac" name="c" nonactionable="False"/>
<tag id="76422fdf-09c0-4902-bbf3-609fe446c08f" name="d" …
```

Fix the collection of parents in TagStore's XML export

---

GTG/core/filters.py
GTG/gtk/browser/sidebar.py

Fixes #1007
The anomaly was caused by a lucky bug. `TagEmptyFilter` was checking for the wrong `self.pane` values except when `Sidebar.__init__` created the object, thus filtering the tags with zero tasks only after startup.  
Now, `TagEmptyFilter` checks for the correct `self.pane` values and considers the newly introduced `show_zero` field. (This field could be used in the future to show and hide tags with zero tasks.)

Always show tags with zero tasks

---

GTG/core/tasks.py

Fixes #1078
If a parent is provided during task creation, all tags of the parent are added to the newly created task.

Inherit the parent's tags when creating a new subtask

---

GTG/core/base_store.py
GTG/core/tasks.py
GTG/gtk/editor/taskview.py
tests/core/test_task.py

Fixes #1077
The cause of the (seemingly) extra empty line was that existing subtasks were [not correctly detected](https://github.com/getting-things-gnome/gtg/blob/b32ec933ba61ba2c6e3de563c5fa79dc3abd1f61/GTG/gtk/editor/taskview.py#L792) and thus moved to the end of the text. This happened because of the mixed use of strings and UUIDs for task IDs.
This PR converts strings to UUIDs when necessary and fixes the related type hints.

Fix the mixed-use of UUID and str for task IDs

---

.github/workflows/unit_tests.yml
.github/workflows/weekly_flatpak.yml
meson.build

Relates to #1093
GTK 4.10 has been required since
https://github.com/getting-things-gnome/gtg/commit/23a986847a61f4744a1e9a323a4f5b353358d2e5
Tested by setting the requirement to 4.13, and getting
```
Run-time dependency gtk4 found: NO (tried cmake)
../meson.build:55:11: ERROR: Dependency lookup for gtk4 with method 'pkgconfig' failed: Invalid version, need 'gtk4' ['>= 4.13'] found '4.12.3'.
```

Require GTK 4.10

---

GTG/backends/generic_backend.py
GTG/core/base_store.py
GTG/core/config.py
GTG/core/filters.py
GTG/core/sorters.py
GTG/core/system_info.py
GTG/core/versioning.py
GTG/gtk/application.py
GTG/gtk/backends/backendstree.py
GTG/gtk/browser/delete_task.py
GTG/gtk/browser/main_window.py
GTG/gtk/browser/search_editor.py
GTG/gtk/browser/sidebar_context_menu.py
GTG/gtk/browser/tag_editor.py
GTG/gtk/colors.py
GTG/gtk/editor/calendar.py
GTG/gtk/editor/editor.py
GTG/gtk/errorhandler.py
GTG/gtk/general_preferences.py
GTG/gtk/plugins.py
GTG/plugins/export/templates.py
GTG/plugins/gamify/gamify.py
GTG/plugins/send_email/sendEmail.py
GTG/plugins/unmaintained/bugzilla/bugzilla.py
tests/core/test_tag_store.py
tests/core/test_task.py
tests/tools/test_tags.py

Relates to #237
With one exception, this is the output of `ruff lint --fix`. The changes look minor - it mostly removes unused imports.
Ruff reports a lot of other errors, including a fair amount of "Undefined name" that indicate broken code paths. We can tackle those separately, and decide whether we want to add Ruff to the pre-commit hook.
This commit in itself is still a good quality of life improvement.
I also did some smoke testing to make sure nothing is obviously broken.

Apply simple Ruff fixes

---

GTG/core/tags.py
GTG/core/tasks.py
tests/core/test_tag_store.py

- Use the _Element class instead of the Element factory for typing.
- Convert tag IDs to UUID during XML parsing. (The same thing caused many problems for tasks.)
- During XML parsing, the `parent` property contains a UUID in the new format. This allowed for some simplifications. A related test case is also fixed.

Fix (almost) every type hint in tags.py

---

GTG/gtk/browser/main_window.py

Pressing ESC now closes the search bar again. Good times
fixes #1003

Add action to dismiss search bar

---

GTG/gtk/browser/main_window.py

Run the `refresh()` function on each pane when the timer runs
Fixes #1073

Refresh all views when day changes

---

.github/workflows/unit_tests.yml
GTG/core/tasks.py
GTG/gtk/editor/editor.py
GTG/gtk/editor/taskview.py
tests/core/test_task.py
tests/core/test_taskview.py

I started to look at #1077 and I thought it would be nice to be able to unit test this type of thing.
A simple unit test for TaskView would be
* create a task
* create a view for it
* check that the title of the view is the title of the task
In the current state of affairs, this is difficult because the code that puts the Task data into the view lives in TaskEditor. But we pass a Task to the constructor of TaskView, so TaskView actually has all the data it needs. So I moved the logic there. I also moved the `is_new()` logic from the TaskEditor down to the Task.
I feel like it should be possible to eventually do this in the TaskView constructor but for now, TaskEditor calls `self.textview.set_text_from_task()` from the same place it used to run that code.
The test triggers a segmentation …

Write unit test for TaskView.get_title()

---

GTG/gtk/browser/main_window.py

Task editors did not re-open because `MainWindow.restore_editor_windows` used strings instead of UUIDs to look up tasks in the data store.

Fix re-opening task editors

---

GTG/core/tasks.py

- use the `_Element` class instead of the `Element` factory for typing
- expect `None` values often used by lxml
- rename the `title` setter to `set_title`
- fix default value for `duplicate_cb`
This fixes every typing error mypy indicates except for the signature errors of some overrides. (I want to investigate the saved searches before looking into those.)

Simple typing fixes for tasks.py

---

.github/workflows/weekly_flatpak.yml
build-aux/org.gnome.GTG.Devel.json

Relates to #708
This fixes the following error:
```
$ flatpak install org.gnome.GTG.Devel_20240530.flatpak
error: The application org.gnome.GTG.Devel/x86_64/master requires the runtime org.gnome.Platform/x86_64/master which was not found
```
by using the latest GNOME runtime, as opposed to the "master" one, which doesn't seem to exist.
Tested by running the workflow on my fork, downloading the artifact from GHA, installing and running the flatpak.

Use GNOME 46 in weekly flatpak

---

.gitignore
snap/snapcraft.yaml

- move snap to core24 which brings GNOME 46
- simplify how liblarch is built
- setup gitignore for expected output

chore: move snap to core24 and GNOME 46

---

GTG/core/tags.py
GTG/core/tasks.py

This PR has two main changes:
- Iterate over all tasks, not just the root elements.
- Consider all descendants of a tag, not just the immediate children.
Because of these bugs, it was impossible to get rid of the `money` tag in the default dataset:
1. Start the program with the default dataset. 
2. Delete the `money` tag in the sidebar.
3. Restart the application.
4. Observe that the `money` tag is absent from the sidebar.
5. Open the _"Learn How to Use Tags and Enable the Sidebar"_ task.
6. Observe the `money` tag reappearing in the sidebar. 
(I discovered this bug while investigating Issue #1115. They might be related, but the described anomaly is different.)

Fixes for 'filter_tag'

---

GTG/plugins/hamster/hamster.py

Catch exception when trying to call hamster via dbus. Needs to be tested with Flatpak
The hamster plugin also needs to be updated for the new core or sent to the unmainted folder, but that's another ticket
Fixes #683

Fix hamster activation

---

GTG/core/base_store.py
GTG/core/clipboard.py
GTG/core/config.py
GTG/core/tags.py
GTG/core/tasks.py
GTG/gtk/backends/parameters_ui/__init__.py
GTG/gtk/browser/adaptive_button.py
GTG/gtk/browser/main_window.py
GTG/gtk/browser/task_pane.py
GTG/gtk/colors.py
GTG/gtk/editor/calendar.py
GTG/gtk/editor/recurring_menu.py
GTG/gtk/errorhandler.py
GTG/plugins/gamify/gamify.py
GTG/plugins/unmaintained/tomboy/tomboy.py
scripts/anonymize_task_file.py
tests/core/test_quickadd.py
tests/core/test_saved_search.py
tests/core/test_tag_store.py
tests/core/test_task.py
tests/core/test_taskview.py

Relates to #237
This is a follow-up to https://github.com/getting-things-gnome/gtg/commit/c2f650f21e50f5d1dad1d9d6226909417656616d
I ran `ruff check` and looked at the errors that Ruff finds but doesn't want to fix automatically.
There are still 13 errors, which all seem to indicate a bug. They are mostly "Undefined name". I will fix them individually.

More Ruff fixes

---

GTG/gtk/browser/main_window.py
GTG/gtk/browser/sidebar.py

Fix sensitivity of start button

---

GTG/gtk/browser/main_window.py
GTG/gtk/browser/task_pane.py
GTG/gtk/errorhandler.py

Fixes #1093.
This commit adds a queue of ExceptionHandlerDialogs, so we only show one at a time. This avoids the scenario where GTG creates dialogs in a loop, making them impossible to close.
If an exception happens while the dialog is opened, its own dialog will pop up when the current one gets closed.
First test with a repro of #1093, raising an exception in the TaskBox constructor. 3 dialogs pop up consecutively, and it's always possible to click on "Continue" to keep GTG running. After that, clicking on a different pane also makes 3 error dialogs pop up in sequence. Interestingly, GTG hangs on the click on the third Continue. I'm not too bothered about it because this emulates a rare case of the system being in a really bad state and it's probably a good idea to exit anyway.
We could …

Add queue of ExceptionHandlerDialogs

---

GTG/core/saved_searches.py
tests/core/test_saved_search.py

- use the `_Element` class instead of the `Element` factory for typing
- convert tag IDs to `UUID` during XML parsing
- expect `None` values returned by lxml
- other minor typing fixes
- fix a related test case

Fix (almost) every typing error in saved_searches.py

---

GTG/core/tags.py

Fixes #1115 
Thanks to this PR, the  `TagStore` keeps track of the models created for child tags and updates them as required triggering a GUI update (similarly to the `TaskStore`). This GUI update prevents the user from deleting a tag twice and crashing the program.

Fix sidebar updates for tags

---

GTG/core/tasks.py

If the task's parent has a due date then we should show sub-tasks as having that due date.
Fix #1072

Look for parent in due date binding

---

GTG/core/datastore.py
GTG/core/dirs.py

The main changes are the following:
- use the `_Element`/`_ElementTree` class instead of the `Element`/`ElementTree` factory for typing,
- expect `None` values returned by lxml,
- expect `None` values in case the methods are used in the wrong order,
- fix the use of undefined variables in `do_first_run_versioning`.
(Please note that `do_first_run_versioning` is never called. Maybe it is a bug or something to be removed.)

Fix most of the typing errors in datastore.py

---

GTG/core/firstrun_tasks.py

The changes are as follows:
- use the `_Element`/`_ElementTree` class instead of the `Element`/`ElementTree` factory for typing
- expect `None` values returned by lxml
- add type hints to the default tasks
- fix the return type of the `generate` function

Fix typing errors in firstrun_tasks.py

---

GTG/core/meson.build
build-aux/org.gnome.GTG.Devel.json
data/org.gnome.GTG.appdata.xml.in.in
meson.build
meson_options.txt

Update base version from 0.6.0 to 0.7-dev.
The idea is that when we're ready to release 0.7, we'll create a 0.7  branch. We'll then update the version to "0.7" on that branch, and "0.8-dev" on master.
Append the short commit hash in development mode (as before)
Append the date in flatpak mode, to help keep track of versions when using the weekly flatpak. Tested the flatpak by running the GHA workflow on my fork.

Improve version name

---

GTG/gtk/data/recurring_menu.ui
GTG/gtk/editor/recurring_menu.py

Fixes #1015
After selecting the desired day in the yearly calendar, the `_update_calendar` method synced the monthly calendar, thus triggering the `_on_monthly_selected` callback. The bug also worked the other way around. 
Now, the `_update_calendar` blocks these callbacks using a `with` statement to prevent the issue.

Fix calendar selection for repeating tasks

---

GTG/core/sorters.py
GTG/gtk/browser/main_window.py
GTG/gtk/browser/task_pane.py
GTG/gtk/data/main_window.ui

This PR adds a couple of buttons to reverse the sorting order (ascending or descending), also converts the sorting options to stateful actions which gives us radio buttons
closes #1021

Sort Order

---

GTG/core/base_store.py
GTG/core/saved_searches.py
GTG/core/tags.py
GTG/core/tasks.py

The only purpose of the `BaseStore.new` and `BaseStore.from_xml` methods is to provide an overview of how to use the subclasses. However, the mismatched signatures caused typing errors. Suppressing these errors instead of simply deleting the base class methods can still provide this "educational" benefit.
Other options would be:
- to use an extra generic parameter in these methods (looks a bit over-complicated...)
- to use composition instead of inheritance (more elegant, but this would probably break existing code and established interfaces)

Suppress mismatched signature errors in type-checking

---

GTG/core/system_info.py

- import `importlib.util` directly to please the type checker
- handle case when `flatpack-version` is not present
- fix the return type of `__get_gtk_version`

Fix typing errors in system_info.py

---

GTG/gtk/browser/task_pane.py

It was possible to reparent a task to itself using drag-and-drop. `TaskPane.check_parent` now checks if the drop target is the same task we are moving.
1. Pick a task and start dragging it over another task.
2. Move it back over itself, and drop it.
3. Observe as the task disappears instead of not doing anything.
By repeating these steps, you can make all of your tasks disappear. They are still in the `gtg_data.xml`, but there is no way accesing them.

Prevent reparenting a task to itself

---

GTG/core/versioning.py

The changes are as follows:
- use the `_Element`/`_ElementTree` class instead of the `Element`/`ElementTree` factory for typing,
- expect `None` values returned by lxml,
- other minor fixes.
Two unresolved lines still reference the `core/xml.py` file removed in e43eee0. This doesn't cause runtime errors because the code in `versioning.py` is currently unreachable (see PR #1133; this is possibly the reason behind issue #1051).

Type fixes for versioning.py

---

GTG/gtk/browser/sidebar.py

Similarly to PR #1149, it was possible to reparent a tag to itself using drag-and-drop. `Sidebar.check_parent` now checks if the drop target is the same tag we are moving.
1. Pick a tag and start dragging it over another tag.
2. Move it back over itself, and drop it.
3. Observe the program freezing and eventually running out of memory.
(If it is not against any current plans, I would be happy to experiment with a common `StoreItem` base class or something similar to prevent such duplicated bugs.)

Prevent reparenting a tag to itself

---

.github/workflows/unit_tests.yml
GTG/core/system_info.py
GTG/gtk/browser/main_window.py
GTG/gtk/tag_completion.py
README.md
build-aux/python3-requirements.yaml
build-aux/requirements.txt
snap/snapcraft.yaml

I think it has been unused since the move to GTK4.
Tested by creating and running the flatpak.

Remove liblarch

---

GTG/backends/generic_backend.py
GTG/core/info.pyi
GTG/core/plugins/engine.py
GTG/core/search.py
GTG/core/sorters.py

The changes are as follows:
- Add some missing type hints. (It looks like `Plugin.missing_dbus` is never actually updated, maybe it can be removed once we are sure that we don't need it. The current type hint is based on an older code version.)
- Add a typing stub for `core/info.py.in`.
- Introduce `TMP_KEYWORDS` to avoid changing types.
- Simplify `TaskTagSorter.get_first_letter` to resolve a missing return error. (Based on my micro-benchmarks, it is still performant.)

Minor type fixes for core

---

GTG/core/base_store.py
GTG/gtk/browser/delete_task.py

When deleting a task and one of its descendants simultaneously, the program crashes. It happens because it tries to remove the descendant twice: once as a selected task and once as the descendant of the other task.
1. Start GTG with the default dataset.
2. Expand the first task (_"Getting Started with GTG (read me first)"_).
3. Select the parent tag and its children.
4. Try to delete them using simultaneously.
5. Observe the crash.
When deleting multiple tasks simultaneously, we should check that a given task was not already removed as the descendant of a previously removed task.

Fix crash when deleting a task and its descendant together

---

GTG/gtk/browser/main_window.py

Created new shortcut keyboard to switch tabs. Use the commands Alt+1, Alt+2 and Alt+3 to execute the shortcuts 
issue #975

Create keyboard shortcuts to switch between Open, Actionable and Closed issue#975

---

GTG/gtk/browser/main_window.py

Some trailing whitespaces caused the automatic tests to fail in the GitHub Action.

Remove trailing whitespaces from main_window.py

---

GTG/core/base_store.py
GTG/core/tags.py
GTG/core/tasks.py
GTG/gtk/browser/sidebar.py
GTG/gtk/browser/task_pane.py
docs/contributors/coding best practices.md
tests/core/test_store_item.py

This is a followup to PR #1151 removing duplicated functionality. The main benefits include:
- reduced code duplication,
- isolated testing of common functionality,
- the possibility of a more targeted testing of the `BaseStore` class (which I would be happy to do).
- introduced a new class that implements common functionality for items in a `BaseStore`,
- added corresponding unit tests,
- fixed a typo in the copyright text.

Introduce the StoreItem base class

---

GTG/core/base_store.py

PR #1158 aimed to remove all outdated `typing.List` references form the `base_store.py` file. However, PR #1159 introduced a new one in the meantime that was not considered by 1158. When 1158 was merged, it caused all sorts of errors (e.g., failing the GHA tests) because of the now missing `typing.List` import.

Remove old List use introduced by another branch from base_store.py

---

GTG/core/base_store.py
GTG/core/saved_searches.py
tests/core/test_base_store.py

I wrote unit tests for BaseStore.remove and discovered 2 bugs along the way:
- When removing an item, the code only considered the children instead of removing all descendants. This resulted in the store being left in an inconsistent state. (This seems related to the scattered use of `BaseStore.refresh_lookup_cache` method.)
- When removing a tree of items, only the root element was reported with a `removed` signal. (If I am not mistaken, the code never relied on this signal, but let's fix it anyway.)
- write unit tests for `BaseStore.remove`,
- ensure that all descendants are recursively removed,
- ensure that a `removed` signal is emitted for each removed item,
- make `SavedSearch` a subclass of `StoreItem` to keep things readable.

Tests and related bugfixes for BaseStore.remove

---

GTG/core/base_store.py
tests/core/test_base_store.py

I wrote unit tests for `BaseStore.parent`. The tests revealed that calling the method with a non-existing `parent_id` changes the list of root elements (`self.data`).
- add unit tests for `BaseStore.parent`,
- ensure that the store is unchanged when called with invalid IDs,
- add helpful error messages to the exceptions.

Tests and a fix for BaseStore.parent

---

GTG/gtk/browser/sidebar.py

Fixes #1130 
- updated the config both when a tag is selected and when tags are unselected,
- disable auto-selection for the saved searches.
The second point is unrelated to the original bug. While testing my solution, it turned out that there was no way of unselecting saved searchs because of the enabled auto-selection.

Remember unselecting tags + disable saved search auto-selection

---

GTG/core/base_store.py
GTG/core/tags.py
GTG/core/tasks.py
GTG/gtk/browser/main_window.py
GTG/gtk/browser/sidebar.py
GTG/gtk/browser/task_pane.py
GTG/gtk/editor/editor.py
tests/core/test_base_store.py
tests/core/test_task.py

I added unit tests for `BaseStore.unparent` and did a bit of refactoring. The only minor thing it revealed was that a `KeyError` was raised even when both IDs existed, but the corresponding items were not in a child-parent relation. 
**The main changes are as follows:**
- add unit tests for `BaseStore.unparent`,
- use `ValueError` instead of `KeyError` when both parameters exist but are not in a child-parent relation,
- simplify the algorithm.
**Note:** `BaseStore.unparent` doesn't actually need the `parent_id` as an extra input since it can be derived as `child.parent.id`. Unparenting is used in around 20 places, so the argument should be relatively easy to remove. Are there any plans or design decisions that could influence this?

Test and refactor BaseStore.unparent

---

GTG/core/firstrun_tasks.py
GTG/core/info.py.in
NEWS
README.md
docs/contributors/git workflow tips.md
docs/contributors/release process and checklist.md
docs/contributors/translating.md
docs/source/releases/v0.3.1.rst
tests/core/test_urlregex.py

Closes #1164
This commit updates the references to wiki.gnome.org, except the ones in the translations (I assume there is a process to mark translations as outdated), and the following:
```
$ ag wiki.gnome.org --ignore po
docs/contributors/git workflow tips.md
31:Pro tip: using a graphical tool like [gitg](https://wiki.gnome.org/Apps/Gitg/), which not only lets you see visually the relationship between the various branches, but also lets you select which lines of which files you want to "stage" to commit, making it INCREDIBLY easier, and letting you make much cleaner, smaller, "atomic" commits. Check out the [Meld](https://meldmerge.org/) tool, too.
docs/contributors/profiling GTG for performance.md
63:![Generated image](https://wiki.gnome.org/Apps/GTG/development?action=AttachFile&do=get& …
```

Update links to old wiki

---

GTG/core/system_info.py

The changes are as follows:
- present the GTK version numbers in "major.minor.micro" order,
- adjust a related docstring.

Fix GTK version numbering in system_info.py

---

GTG/gtk/editor/editor.py
GTG/gtk/editor/taskview.py

Fixes #1138
When the task editor gets closed, it first calls
`self.textview.process()` which, after processing, calls `self.save_cb()`, which is set to `TaskEditor.light_save()`. This only calls `TaskEditor.save()` at most every 7 seconds. So if you crete a new task and close its editor within 7 seconds, the task doesn't get saved.
This commit makes `TaskEditor.desctruction()` call `TaskEditor.save()`, to make sure the task is saved properly before closing the task popup.

Save task before closing editor

---

build-aux/org.gnome.GTG.Devel.json
build-aux/python3-requirements.yaml
build-aux/requirements.txt

Fixes https://github.com/getting-things-gnome/gtg/issues/1155
Fixes https://github.com/getting-things-gnome/gtg/issues/1179

Bump runtime to 47

---

GTG/gtk/browser/main_window.py

This is a follow-up to PR #1183.
Calling `Task.toggle_dismiss` caused the task to reactivate if it was already dismissed. 
1. Create a nested task structure of 5 tasks: *a -> b -> c -> d -> e*.
2. Ensure that they are all visible in the main window.
3. Select all 5 tasks.
4. Try to dismiss them all at once using the *right-click/Dismiss* option. 
5. Observe that they are still active except *e*.
**Note:** While debugging, I noticed that certain tasks are dismissed multiple times since they are selected and they are descendants of other tasks.

Use Task.set_status to mark tasks as dismissed

---

GTG/core/base_store.py
GTG/core/tags.py
GTG/core/tasks.py
tests/core/test_store_item.py

The main motivation behind this PR is to simplify the cases when class A emits a signal on class B because class C did something. E.g., the `Task` class can manage the update of its `has_children` property alone. (Overriding these methods can also help realising when a task is no longer actionable.)
**The main changes are as follows:**
- introduce the `StoreItem.add_child` and `StoreItem.remove_child` methods (automatically trigger signals and potentially other functionality)
- add unit tests for the methods above
- leverage these methods in the `BaseStore`, `TaskStore` and `TagStore`

Convenience functions for adding and removing children

---

GTG/backends/backend_caldav.py
GTG/core/plugins/api.py
GTG/core/tags.py

This fixes a new issues found by `ruff check`.
There are a few more, but they need to be looked into individually. They are instances of the code being left in an inconsistent state.

Small ruff fixes

---

GTG/gtk/data/style.css

This removes the weird white bar at the top of the list in dark style.
Fixes https://github.com/getting-things-gnome/gtg/issues/1009

Remove top border in `.task-list`

---

GTG/core/config.py

This removes the warning "Child name 'default' not found in GtkStack"

Change default view to `open_view`

---

GTG/gtk/browser/main_window.py
GTG/gtk/data/main_window.ui

The search bar's activation and deactivation are split into different methods, as the way the search bar should behave differently on a case-by-case basis.
This also makes use of modern APIs and methods provided by GTK, which should ease maintenance.
Fixes https://github.com/getting-things-gnome/gtg/issues/952

Rework search bar

---

.github/workflows/unit_tests.yml

The GHA fails because of some dependency problem related to PyGObject. This can be avoided by specifying the exact version of PyGObject that matches the GNOME SDK.

Fix automatic unit test dependencies

---

GTG/core/saved_searches.py

This closes #1005, which is originally about tags, and the saved search related part is only mentioned in the discussion). However, the tag related part was already fixed in PR #1131. 
The solution is simple: when a saved search is deleted, the corresponding `ListStore` is also updated.

Remove deleted saved searches from the UI

---

GTG/gtk/browser/task_pane.py
GTG/gtk/data/style.css

The solution mixes the old styling with the new `.rich-list` formatting while ensuring that spacing values are increments of 6 pixels.
This fixes GitHub issue #1206.

Ensure that colouring fills the entire row in the task list

---

GTG/core/base_store.py
GTG/core/tasks.py
GTG/gtk/browser/task_pane.py
GTG/plugins/hamster/hamster.py
tests/core/test_base_store.py

This is a follow-up PR of #1208
The basic idea is to rely on signaling instead of direct calls to update the different `TreeListModel` instances in `FilteredTaskTreeManager`. This change allowed many simplifications, and I believe it can facilitate other future bug fixes (e.g., #1039).
Another notable change is that the "removed" signal now contains the removed item instead of the ID. This was necessary since the ID itself wasn't that useful once the item was deleted. (This changes the original signal specification, but it was not used anywhere else in the code.)

Use signals instead of direct calls to update `TreeListModel` instances

---

GTG/gtk/tag_completion.py

This is a follow-up of [my recent profiling](https://github.com/getting-things-gnome/gtg/pull/1215#issuecomment-2952771547) showing increased runtime in the `TagCompletion` class. While working, I also noticed a small bug in the code. 
**The main changes are as follows:**
- Fill up `TagCompletion.tags` with presorted values. (This reduced the runtime of the `Gtk.ListStore` population from 313.30s to 0.16s on my dataset containing 3621 tags.)
- Take into account that `Tag.name` does not have a leading `@` sign.

Speed up (and fix) TagCompletion initialisation

---

.github/workflows/unit_tests.yml

The automatic GHA tests are failing because it does not find the *vobject* package. PR #1219 passed when I opened it, but the exact same code failed after the merge. The difference seems to be that the GHA moved to a *cladav* version not requiring *vobject* anymore.
**The changes are as follows:**
- Require the same *caldav* version as in the flatpak build.
- Add *vobject* as an explicit dependency.

Fix automatic unit tests

---

GTG/gtk/browser/sidebar.py

When unselecting tags when a search is selected we don't want to block the signal, so that filtering changes and we can search across all tags.
This fixes the last part of #390 
closes #390

Fix toggling saved searches

---

GTG/core/tasks.py
GTG/gtk/browser/main_window.py
GTG/gtk/browser/task_pane.py

I discovered two somewhat related bugs during testing.
**Steps to reproduce the first bug:**
1. Start GTG with the default dataset.
2. Delete all tasks.
3. Select a tag.
4. Add a task via quick add and observe a crash.
This happens because GTG tries to select the last task in the task list even when it is empty. The original intention was probably to select the newly added task. (Note that it is still possible to have an empty list, e.g., when in the Closed or Actionable view.) I removed the `select_last` method since it wasn't used anywhere else.
**Fixing the crash revealed the second bug:** the newly added task is not visible in the task list. 
This is solved by the new `TaskStore.add_tags` method that emits a signal when the tags are added. It accepts a list of tags but emits only a …

Fix quick add with a tag

---

GTG/core/datastore.py
GTG/gtk/browser/tag_editor.py

Ancestor tag counters were off in the sidebar even after a restart. 
1. Create a nested tag structure with the following new tags: _x > y > z_
2. Create a task with tag _z_. (The counters are wrong here, too, but that is another story.)
3. Restart GTG.
4. Observe the faulty counters in the sidebar (_x_ and _y_ have 0 instead of 1).
The fix prefers `DataStore.update_tag_stats` over `DataStore.refresh_task_count` to trigger an update in the sidebar stats.

Update the sidebar counters after stat recalculations

---

GTG/core/datastore.py
GTG/core/tasks.py

`TaskStore.filter` only considered root tasks in some cases, causing wrong sidebar counters and faulty task purging.
1. Create a new nested task structure: _a > b > c_
2. Create a new tag: _z_.
3. Tag _c_ with _z_.
4. Restart GTG.
5. Go to the Actionable view
6. Observe the wrong counter value for _z_ (0 instead of 1).
7. (If you mark _c_ as completed, you can not purge it.)

Consider all tasks in `TaskStore.filter`

---

GTG/core/datastore.py
GTG/core/filters.py
GTG/core/tags.py
GTG/core/tasks.py
GTG/gtk/browser/delete_tag.py
GTG/gtk/browser/main_window.py
GTG/gtk/browser/modify_tags.py
GTG/gtk/browser/sidebar.py
GTG/gtk/editor/editor.py

Closes #1023 
While considering different options, I realised that if a task is changed in a way that it influences at least one counter, it can possibly impact any other counters as well. The complication mainly revolves around actionability. E.g., if the user completes/removes/dismisses a task, it can impact: all the tags applied to that task, their ancestor tags, and the same can be true for the parent task, which can possibly become actionable.
**Based on the previous observation, I made the following changes:**
- Move stat-related calculations to its own class (`TagStats`). The goal is to prevent logic from being scattered and making other methods more complex. This could also help recognise bugs and optimise the calculations.
- Connected major task events with stat recalculations. …

Fix sidebar counters
